import type {Metadata} from "next";
export const metadata:Metadata={title:"Docs | REKTRUN",description:"The REKTRUN field manual: controls, combat, progression, scoring and onchain rules."};
const sections=[
 ["01","OVERVIEW","REKTRUN is a browser-native action platformer set in a corrupted forest network. Each run combines traversal, melee combat, randomized obstacles, collectible shards, an unstoppable pursuer, and a final Guardian arena."],
 ["02","CONTROLS","Move with A/D or the arrow keys. Jump with Space or W. Attack with left click or J. Throw with right click or K. Dash with Shift. Mobile controls appear automatically on touch devices."],
 ["03","RUNNERS & GEAR","Each runner changes speed, health, jump behavior, or shard collection. Gear adds attack power, movement bonuses, magnet range, and critical effects. Build choices are made before a run and remain active until it ends."],
 ["04","THE HUNTER","A giant invulnerable creature follows from behind during normal stages. It moves slower than the runner, cannot be damaged, and deals contact damage. When the Guardian arena begins, the hunter and all ordinary enemies disappear."],
 ["05","GUARDIANS","Four Guardians use different attack families: ground waves and falling bolts, roots and arc projectiles, radial volleys and lasers, or mixed cosmic patterns. Watch the telegraph, move first, then punish the recovery window."],
 ["06","SCORING","Distance, enemies defeated, Guardians cleared, collected shards, and remaining health contribute to the run result. Only authenticated, validated runs are eligible for the public seasonal leaderboard."],
 ["07","ROBINHOOD CHAIN","REKTRUN supports Robinhood Chain only. Wallet connection is required for score submission and reward eligibility; casual play remains available before connecting. Unsupported networks are rejected at submission."],
 ["08","SEASONS & REWARDS","Seasonal leaderboard placement may be used for token airdrop eligibility. Exact allocations, anti-cheat requirements, snapshot timing, exclusions, and claim instructions will be announced before a season closes. A leaderboard position is not a guarantee of reward."],
 ["09","FAIR PLAY","Automated input, modified clients, impossible movement, replayed submissions, and score manipulation may invalidate a run. Competitive records should be reproducible from signed run data and server-side validation."],
 ["10","FAQ","No installation is required. Use a modern desktop browser for the best experience. Audio begins after user interaction. If controls stop responding, click inside the game canvas and resume from the pause menu."]
];
export default function Docs(){return <main className="docsPage"><header><a href="/">← REKTRUN</a><nav><a href="/play">PLAY</a><a href="/play">LEADERBOARD</a><a className="active" href="/docs">DOCS</a></nav></header><section className="docsHero"><small>FIELD MANUAL / SEASON 01</small><h1>ENTER THE<br/><i>WILD CHAIN.</i></h1><p>Everything required to survive a run, submit a verified score, and compete on Robinhood Chain.</p><a href="/play">PLAY NOW →</a></section><aside>{sections.map(s=><a href={`#s${s[0]}`} key={s[0]}>{s[0]} / {s[1]}</a>)}</aside><section className="docsContent">{sections.map(s=><article id={`s${s[0]}`} key={s[0]}><small>{s[0]}</small><h2>{s[1]}</h2><p>{s[2]}</p></article>)}</section><footer><span>REKTRUN DOCS / V0.1</span><a href="/play">BEGIN RUN →</a></footer></main>}
