import {sfx,startMusic} from "./gameAudio";

export type ArcadeStats={score:number;distance:number;gems:number;rekt:number};
type World={id:string;color:string;sky:string;land:string};
type Runner={id:string;color:string};type Gear={id:string};
type Options={world:World;runner:Runner;gear:Gear;onStats:(s:ArcadeStats)=>void;onFinish:(s:ArcadeStats,durationMs:number)=>void};
type Rect={x:number;y:number;w:number;h:number};
type Enemy=Rect&{kind:"walker"|"flyer"|"shooter";hp:number;cool:number;vx:number;vy?:number;grounded?:boolean;jumpClock?:number;hurt?:number};
type Pickup=Rect&{kind:"gem"|"heart"|"ammo"};
type Shot=Rect&{vx:number;vy:number;enemy:boolean;kind?:"bolt"|"orb"|"wave"};
type Hazard=Rect&{kind:"spike"|"mushroom"|"pit"|"laser"|"saw"};
type Platform=Rect&{kind:"stone"|"bridge"|"lift";baseY:number;phase:number};
type Decor=Rect&{kind:0|1|2|3|8|9|10|11};
const hit=(a:Rect,b:Rect)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));

export function startArcadeGame(canvas:HTMLCanvasElement,keys:Set<string>,o:Options){
 const ctx=canvas.getContext("2d")!,sprites=new Image(),roster=new Image(),levelArt=new Image();sprites.src="/game-sprites.png";roster.src="/roster-bosses.png";levelArt.src="/level-atlas.png";startMusic();const runnerIndex=Math.max(0,["byte","nova","ember","void"].indexOf(o.runner.id)),bossIndex=Math.max(0,["base","forest","lava","cosmic"].indexOf(o.world.id));let stopped=false,frame=0,last=performance.now(),elapsed=0,lastHud=0,spawnClock=.8,pattern=0,camera=0,distance=0,gems=0,kills=0,bosses=0,nextBoss=520,shake=0,boss:null|{x:number;y:number;w:number;h:number;hp:number;max:number;state:number;clock:number} = null;
 const p={x:190,y:200,w:66,h:88,vx:0,vy:0,hp:5,maxHp:5,ammo:3,maxAmmo:15,grounded:false,lastGround:0,jumpQueued:-99,dash:0,dashCd:0,slide:0,attack:0,attackCd:0,invuln:0,face:1};
 const chaser={x:-255,y:0,w:270,h:300,speed:30};
 const was={jump:false,dash:false,melee:false,ranged:false};
 if(o.runner.id==="ember"||o.gear.id==="shield")p.hp=p.maxHp=7;
 const highJump=o.runner.id==="void"||o.gear.id==="boots",doubleGems=o.runner.id==="nova"||o.gear.id==="magnet",meleeRange=o.gear.id==="blade"?130:95;
 let enemies:Enemy[]=[],pickups:Pickup[]=[],shots:Shot[]=[],hazards:Hazard[]=[],platforms:Platform[]=[],decors:Decor[]=[],echoes:{x:number;y:number;a:number}[]=[],particles:{x:number;y:number;vx:number;vy:number;a:number;c:string}[]=[],pressed=new Set<string>();
 const resize=()=>{const d=Math.min(devicePixelRatio,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)},pointerDown=(e:PointerEvent)=>{if(e.button===0)pressed.add("melee");if(e.button===1)pressed.add("dash");if(e.button===2)pressed.add("ranged");e.preventDefault()},blockMenu=(e:Event)=>e.preventDefault();resize();canvas.style.cursor="crosshair";addEventListener("resize",resize);canvas.addEventListener("pointerdown",pointerDown);canvas.addEventListener("contextmenu",blockMenu);
 const burst=(x:number,y:number,c:string,n=9)=>{for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*240,vy:(Math.random()-.7)*220,a:1,c})};
 const sprite=(col:number,row:number,x:number,y:number,w:number,h:number,flip=false)=>{if(!sprites.complete||!sprites.naturalWidth)return false;const sw=sprites.naturalWidth/4,sh=sprites.naturalHeight/4;ctx.save();if(flip){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(sprites,col*sw,row*sh,sw,sh,0,0,w,h)}else ctx.drawImage(sprites,col*sw,row*sh,sw,sh,x,y,w,h);ctx.restore();return true};
 const rosterSprite=(col:number,row:number,x:number,y:number,w:number,h:number,flip=false)=>{if(!roster.complete||!roster.naturalWidth)return false;const sw=roster.naturalWidth/4,sh=roster.naturalHeight/4;ctx.save();if(flip){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(roster,col*sw,row*sh,sw,sh,0,0,w,h)}else ctx.drawImage(roster,col*sw,row*sh,sw,sh,x,y,w,h);ctx.restore();return true};
 const envSprite=(col:number,row:number,x:number,y:number,w:number,h:number)=>{if(!levelArt.complete||!levelArt.naturalWidth)return false;const sw=levelArt.naturalWidth/4,sh=levelArt.naturalHeight/4;ctx.drawImage(levelArt,col*sw,row*sh,sw,sh,x,y,w,h);return true};
 function spawnPattern(W:number,H:number,diff:number){const ground=H-105,roll=Math.floor(Math.random()*10),choice=roll===pattern?(roll+1+Math.floor(Math.random()*8))%10:roll,far=W+80,gap=140-diff*35;pattern=choice;if(Math.random()<.72){const kind=[0,1,2,3,8,9,10,11][Math.floor(Math.random()*8)] as Decor["kind"];decors.push({x:far+Math.random()*260,y:ground-(kind<4?235:150),w:kind<4?190:120,h:kind<4?220:140,kind})}
  if(choice===0){for(let i=0;i<3;i++)enemies.push({x:far+i*gap,y:ground-38,w:38,h:38,kind:"walker",hp:1,cool:0,vx:75+diff*80})}
  if(choice===1){enemies.push({x:far,y:ground-150,w:42,h:32,kind:"flyer",hp:1,cool:0,vx:95+diff*70});pickups.push({x:far+90,y:ground-175,w:18,h:18,kind:"gem"})}
  if(choice===2){hazards.push({x:far,y:ground-24,w:58,h:24,kind:"spike"});pickups.push({x:far+18,y:ground-105,w:18,h:18,kind:"gem"});pickups.push({x:far+58,y:ground-145,w:18,h:18,kind:"gem"})}
  if(choice===3){hazards.push({x:far,y:ground-25,w:65,h:25,kind:"mushroom"});enemies.push({x:far+175,y:ground-38,w:38,h:38,kind:"walker",hp:1,cool:0,vx:80})}
  if(choice===4){enemies.push({x:far,y:ground-46,w:44,h:46,kind:"shooter",hp:1,cool:.7,vx:35});pickups.push({x:far+140,y:ground-65,w:22,h:22,kind:"ammo"})}
  if(choice===5){hazards.push({x:far,y:ground,w:145,h:38,kind:"pit"});for(let i=0;i<3;i++)pickups.push({x:far+35+i*38,y:ground-105-Math.sin(i*Math.PI/2)*55,w:18,h:18,kind:"gem"})}
  if(choice===6){pickups.push({x:far,y:ground-85,w:22,h:22,kind:p.hp<p.maxHp/2?"heart":"gem"});enemies.push({x:far+130,y:ground-145,w:42,h:32,kind:"flyer",hp:1,cool:0,vx:100})}
  if(choice===7){for(let i=0;i<4;i++){const y=ground-105-(i%3)*105;platforms.push({x:far+i*205,y,w:190,h:38,kind:i===2?"lift":"stone",baseY:y,phase:Math.random()*6});pickups.push({x:far+78+i*205,y:y-48,w:22,h:22,kind:"gem"})}}
  if(choice===8){hazards.push({x:far,y:ground-195,w:90,h:195,kind:"laser"});platforms.push({x:far+180,y:ground-145,w:230,h:34,kind:"bridge",baseY:ground-145,phase:0});enemies.push({x:far+275,y:ground-201,w:54,h:56,kind:"shooter",hp:2,cool:.4,vx:28})}
  if(choice===9){hazards.push({x:far,y:ground-70,w:70,h:70,kind:"saw"});hazards.push({x:far+185,y:ground-28,w:90,h:28,kind:"spike"});platforms.push({x:far+315,y:ground-185,w:245,h:42,kind:"stone",baseY:ground-185,phase:0});platforms.push({x:far+610,y:ground-320,w:220,h:42,kind:"stone",baseY:ground-320,phase:0});enemies.push({x:far+390,y:ground-245,w:58,h:60,kind:Math.random()>.5?"walker":"flyer",hp:2,cool:0,vx:110})}
  if(Math.random()<.58){const blocks=2+Math.floor(Math.random()*3);for(let i=0;i<blocks;i++){const y=ground-110-i*98;platforms.push({x:far+510+i*165,y,w:175,h:38,kind:"stone",baseY:y,phase:0})}}
 }
 function killEnemy(e:Enemy){e.hp=0;kills++;shake=7;sfx("hit");burst(e.x+e.w/2,e.y+e.h/2,o.world.color,18);if(Math.random()<.7)pickups.push({x:e.x,y:e.y,w:18,h:18,kind:"gem"})}
 function damage(n=1){if(p.invuln>0)return;p.hp-=n;p.invuln=2;shake=12;sfx("hurt");burst(p.x+p.w/2,p.y+p.h/2,"#ff476f",18);if(p.hp<=0)finish()}
 function finish(){if(stopped)return;stopped=true;const s={distance:Math.floor(distance),gems,kills,rekt:kills,score:Math.floor(distance+gems*120+kills*200)};o.onFinish(s,Math.floor(elapsed));cleanup()}
 function cleanup(){cancelAnimationFrame(frame);removeEventListener("resize",resize);canvas.removeEventListener("pointerdown",pointerDown);canvas.removeEventListener("contextmenu",blockMenu);canvas.style.cursor="";canvas.style.transform=""}
 function update(dt:number,now:number){const W=innerWidth,H=innerHeight,ground=H-105,diff=clamp(distance/2000,0,1),left=keys.has("KeyA")||keys.has("ArrowLeft"),right=keys.has("KeyD")||keys.has("ArrowRight"),down=keys.has("KeyS")||keys.has("ArrowDown"),jump=keys.has("Space")||keys.has("KeyW")||keys.has("ArrowUp"),dash=keys.has("ShiftLeft")||keys.has("ShiftRight"),melee=keys.has("KeyJ")||keys.has("KeyX"),ranged=keys.has("KeyK")||keys.has("KeyC"),jumpPressed=jump&&!was.jump,dashPressed=(dash&&!was.dash)||pressed.delete("dash"),meleePressed=(melee&&!was.melee)||pressed.delete("melee"),rangedPressed=(ranged&&!was.ranged)||pressed.delete("ranged");
  if(jumpPressed)p.jumpQueued=now;if((now-p.jumpQueued<250)&&(p.grounded||now-p.lastGround<200)){p.vy=highJump?-790:-720;p.grounded=false;p.jumpQueued=-99}if(!jump&&p.vy<0)p.vy+=1280*dt;
  const dir=(right?1:0)-(left?1:0);if(dir)p.face=dir;const target=dir*(dash&&p.dashCd<=0?580:250);p.vx+=(target-p.vx)*Math.min(1,(p.grounded?10:5)*dt);if(!dir)p.vx*=Math.max(0,1-7*dt);
  if(dashPressed&&p.dashCd<=0){p.dash=.38;p.dashCd=1.1;p.vx=p.face*580;sfx("dash")}p.dash=Math.max(0,p.dash-dt);p.dashCd=Math.max(0,p.dashCd-dt);if(p.dash>0){echoes.push({x:p.x,y:p.y,a:.55});p.vx=p.face*580}
  if(down&&p.grounded&&Math.abs(p.vx)>90){p.slide=.55;p.h=50}else if(p.slide<=0){p.h=88}p.slide=Math.max(0,p.slide-dt);
  p.attackCd=Math.max(0,p.attackCd-dt);p.attack=Math.max(0,p.attack-dt);if(meleePressed&&p.attackCd<=0){p.attack=.2;p.attackCd=.36;sfx("slash")}if(rangedPressed&&p.attackCd<=0&&p.ammo>0){p.ammo--;p.attackCd=.45;sfx("shot");shots.push({x:p.x+(p.face>0?p.w:-18),y:p.y+19,w:18,h:8,vx:p.face*620,vy:0,enemy:false})}
  const oldBottom=p.y+p.h;p.vy+=1280*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.x=clamp(p.x,70,W-360);
  const landing=platforms.find(q=>p.vy>=0&&p.x+p.w>q.x&&p.x<q.x+q.w&&oldBottom<=q.y+9&&p.y+p.h>=q.y);if(landing){p.y=landing.y-p.h;p.vy=0;p.grounded=true;p.lastGround=now}else{const underPit=hazards.some(h=>h.kind==="pit"&&p.x+p.w>h.x&&p.x<h.x+h.w);if(p.y+p.h>=ground&&!underPit){p.y=ground-p.h;p.vy=0;p.grounded=true;p.lastGround=now}else p.grounded=false}platforms.forEach(q=>{if(!hit(p,q)||p.grounded)return;if(p.vx>0&&p.x+p.w-q.x<38){p.x=q.x-p.w;p.vx=0}else if(p.vx<0&&q.x+q.w-p.x<38){p.x=q.x+q.w;p.vx=0}});if(p.y>H+80)damage(99);
  const cameraLine=W*.43,scroll=boss?0:Math.max(0,p.x-cameraLine)*5.2*dt;p.x-=scroll;camera+=scroll;distance+=scroll/10;p.invuln=Math.max(0,p.invuln-dt);
  chaser.y=ground-chaser.h;chaser.x+=chaser.speed*dt;
  if(hit(p,chaser)){damage();p.vx=Math.max(p.vx,390);p.vy=-220;chaser.x-=145;shake=18}
  if(!boss&&distance>=nextBoss){bosses++;nextBoss+=620;boss={x:W+100,y:ground-285,w:245,h:285,hp:10+bosses*3,max:10+bosses*3,state:0,clock:1.2};sfx("boss");enemies=[];hazards=[];platforms=[]}
  if(!boss){spawnClock-=dt;if(spawnClock<=0){spawnPattern(W,H,diff);spawnClock=Math.max(.72,1.8-diff*.75)}}
  [...enemies,...pickups,...hazards,...platforms,...decors].forEach(e=>e.x-=scroll);platforms.forEach(q=>{if(q.kind==="lift")q.y=q.baseY+Math.sin(now/650+q.phase)*58});shots.forEach(s=>{s.x+=(s.vx-(s.enemy?scroll*.16:scroll))*dt;s.y+=s.vy*dt});
  enemies.forEach(e=>{e.hurt=Math.max(0,(e.hurt||0)-dt);const dx=p.x-e.x;if(e.kind==="flyer"){e.vx+=(Math.sign(dx)*(125+diff*75)-e.vx)*dt*2.4;e.x+=e.vx*dt;e.y+=Math.sin(now/220+e.x/75)*72*dt+Math.sign(p.y-e.y)*28*dt}else{e.jumpClock=(e.jumpClock||Math.random()*1.4)-dt;const chase=Math.sign(dx)*(e.kind==="shooter"?62:115+diff*80);e.vx+=(chase-e.vx)*Math.min(1,dt*5);e.x+=e.vx*dt;e.vy=(e.vy||0)+1280*dt;const old=e.y+e.h;e.y+=e.vy*dt;let floor=ground;for(const q of platforms)if(e.x+e.w>q.x&&e.x<q.x+q.w&&old<=q.y+10&&e.y+e.h>=q.y)floor=Math.min(floor,q.y);if(e.y+e.h>=floor){e.y=floor-e.h;e.vy=0;e.grounded=true;if((Math.abs(dx)>75&&(e.jumpClock||0)<=0)||platforms.some(q=>q.x<e.x+e.w+45&&q.x+q.w>e.x&&q.y<e.y+e.h-35)){e.vy=-610-Math.random()*90;e.grounded=false;e.jumpClock=.8+Math.random()*1.3}}else e.grounded=false}if(e.kind==="shooter"){e.cool-=dt;if(e.cool<=0&&Math.abs(dx)<620){e.cool=Math.max(.75,1.6-diff*.55);shots.push({x:e.x+(dx>0?e.w:-18),y:e.y+18,w:18,h:11,vx:Math.sign(dx)*(300+diff*130),vy:(p.y-e.y)*.18,enemy:true})}}if(hit(p,e)){if(p.vy>120&&p.y+p.h<e.y+e.h*.55){killEnemy(e);p.vy=-540}else{damage();p.x+=Math.sign(p.x-e.x)*35;p.vx=Math.sign(p.x-e.x)*260}}});
  if(p.attack>0){const a={x:p.face>0?p.x+p.w-8:p.x-meleeRange+8,y:p.y+4,w:meleeRange,h:p.h-8};enemies.forEach(e=>{if(e.hp>0&&hit(a,e)){e.hurt=.2;killEnemy(e)}});if(boss&&hit(a,boss)){boss.hp--;p.attack=0;p.x-=p.face*22;p.vx=-p.face*170;shake=9;burst(boss.x,boss.y+p.h,o.world.color,12)}}
  pickups=pickups.filter(q=>{if(hit(p,q)){if(q.kind==="gem")gems+=doubleGems?2:1;if(q.kind==="heart")p.hp=Math.min(p.maxHp,p.hp+2);if(q.kind==="ammo")p.ammo=Math.min(p.maxAmmo,p.ammo+3);sfx("pickup");burst(q.x,q.y,q.kind==="heart"?"#ff48d7":q.kind==="ammo"?"#f7f7ff":"#65f8ff",6);return false}return q.x>-50});
  hazards.forEach(h=>{if(hit(p,h)){if(h.kind==="mushroom"){p.vy=-720;p.y=h.y-p.h-2}else if(h.kind==="spike"||h.kind==="laser"||h.kind==="saw")damage();else if(h.kind==="pit"&&p.grounded===false){/* fall naturally */}}});
  shots=shots.filter(s=>{if(s.enemy&&hit(p,s)){damage();return false}if(!s.enemy){const e=enemies.find(e=>e.hp>0&&hit(s,e));if(e){killEnemy(e);return false}if(boss&&hit(s,boss)){boss.hp--;shake=5;burst(s.x,s.y,o.world.color,10);return false}}return s.x>-30&&s.x<W+30});enemies=enemies.filter(e=>e.hp>0&&e.x>-100);hazards=hazards.filter(h=>h.x>-200);platforms=platforms.filter(q=>q.x>-250);decors=decors.filter(q=>q.x>-300);
  if(boss){boss.x+=(W-350-boss.x)*Math.min(1,dt*2.2);boss.clock-=dt;if(boss.clock<=0){boss.state=(boss.state+1)%4;boss.clock=Math.max(.65,1.65-diff*.5);if(boss.state===0)for(let i=0;i<2;i++)shots.push({x:boss.x,y:boss.y+75+i*55,w:34,h:20,vx:-390-i*55,vy:0,enemy:true,kind:"wave"});if(boss.state===1)for(let i=0;i<5;i++)shots.push({x:boss.x,y:boss.y+45,w:23,h:23,vx:-270-i*28,vy:-240+i*105,enemy:true,kind:"orb"});if(boss.state===2)for(let i=0;i<2;i++)enemies.push({x:boss.x-20-i*65,y:ground-52,w:52,h:52,kind:i?"walker":"shooter",hp:1,cool:.35,vx:120});if(boss.state===3)hazards.push({x:p.x+180,y:ground-28,w:125,h:28,kind:"spike"})}shots.forEach(s=>{if(s.enemy&&s.kind==="orb")s.vy+=390*dt});if(hit(p,boss)){damage(2);p.x=boss.x-p.w-8;p.vx=-390;p.vy=-250;shake=20}if(boss.hp<=0){kills+=5;gems+=10;burst(boss.x+70,boss.y+90,o.world.color,35);boss=null;spawnClock=1.6}}
  echoes.forEach(e=>e.a-=dt*2.6);echoes=echoes.filter(e=>e.a>0);particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=450*dt;q.a-=dt*1.7});particles=particles.filter(q=>q.a>0);shake=Math.max(0,shake-dt*28);canvas.style.transform=shake>0?`translate(${(Math.random()-.5)*shake}px,${(Math.random()-.5)*shake}px) scale(1.006)`:"";
  was.jump=jump;was.dash=dash;was.melee=melee;was.ranged=ranged;if(now-lastHud>90){lastHud=now;o.onStats({distance:Math.floor(distance),gems,rekt:kills,score:Math.floor(distance+gems*120+kills*200)})}
 }
 function draw(now:number){const W=innerWidth,H=innerHeight,ground=H-105,zone=Math.floor(camera/2300)%4,accent=[o.world.color,"#65dfff","#ff8a32","#bd5cff"][zone];ctx.fillStyle=["#061713","#07162d","#260d13","#120720"][zone];ctx.fillRect(0,0,W,H);
  ctx.globalAlpha=.16;ctx.fillStyle=accent;ctx.beginPath();ctx.arc(W*.72-(camera*.018)%220,H*.2,165,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.28;ctx.strokeStyle=accent;ctx.lineWidth=5;ctx.stroke();ctx.globalAlpha=1;
  for(let i=0;i<85;i++){let sx=(i*173-camera*(i%4+1)*.035)%W;if(sx<0)sx+=W;const sy=(i*67)%(ground*.66);ctx.fillStyle=i%9===0?accent:"#dff8ee";ctx.globalAlpha=.35+(i%4)*.14;ctx.fillRect(sx,sy,i%11===0?4:2,i%11===0?4:2)}ctx.globalAlpha=1;
  const ridge=(speed:number,base:number,color:string,step:number)=>{ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,H);for(let x=-step;x<W+step;x+=step){const wx=x+camera*speed,peak=base-Math.sin(wx*.005)*55-Math.sin(wx*.014)*30;ctx.lineTo(x,peak)}ctx.lineTo(W,H);ctx.fill()};ridge(.08,ground-315,"#0b1830",185);ridge(.18,ground-230,"#102b2a",150);
  ctx.fillStyle="#142e29";for(let i=-2;i<13;i++){const rx=i*230-(camera*.27)%230,h=95+(i%4)*42;ctx.fillRect(rx,ground-160-h,70,h);ctx.fillRect(rx-18,ground-168-h,106,12);ctx.fillStyle=accent;ctx.globalAlpha=.22;ctx.fillRect(rx+28,ground-145-h,12,h-18);ctx.globalAlpha=1;ctx.fillStyle="#142e29"}
  ctx.strokeStyle=accent;ctx.globalAlpha=.38;ctx.lineWidth=3;for(let i=-2;i<12;i++){const vx=i*250-(camera*.34)%250;ctx.beginPath();ctx.moveTo(vx,-10);ctx.bezierCurveTo(vx+35,100,vx-25,170,vx+20,290);ctx.stroke();for(let y=65;y<260;y+=48){ctx.fillStyle=accent;ctx.fillRect(vx+Math.sin(y)*9,y,6,13)}}ctx.globalAlpha=1;
  ctx.fillStyle="#06130d";for(let i=-2;i<20;i++){const tx=i*125-(camera*.5)%125;ctx.fillRect(tx,ground-85,16,85);ctx.beginPath();ctx.moveTo(tx-45,ground-50);ctx.lineTo(tx+8,ground-170-(i%3)*18);ctx.lineTo(tx+56,ground-50);ctx.fill()}ctx.fillStyle=accent;ctx.fillRect(0,ground,W,8);ctx.fillStyle="#07150e";ctx.fillRect(0,ground+8,W,H-ground);ctx.fillStyle="#294b35";for(let g=-40;g<W;g+=42){ctx.fillRect(g-camera%42,ground+11,29,10);ctx.fillRect(g+10-camera%42,ground+27,19,9)}ctx.strokeStyle=accent;ctx.globalAlpha=.22;for(let g=0;g<W;g+=62){ctx.beginPath();ctx.moveTo(g-camera%62,ground);ctx.lineTo(g-camera%62,H);ctx.stroke()}ctx.globalAlpha=1;
  decors.forEach(drawDecor);drawChaser();platforms.forEach(drawPlatform);echoes.forEach(e=>{ctx.globalAlpha=e.a;drawRunner(ctx,e.x,e.y,o.runner.color,p.face,p.h,false)});ctx.globalAlpha=1;hazards.forEach(h=>drawHazard(h));pickups.forEach(q=>drawPickup(q,now));enemies.forEach(e=>drawEnemy(e));shots.forEach(s=>{const col=!s.enemy?"#f7f7ff":s.kind==="orb"?"#b764ff":s.kind==="wave"?"#ff9a32":"#ff536f";ctx.fillStyle=col;ctx.shadowBlur=26;ctx.shadowColor=col;if(s.kind==="orb"){ctx.beginPath();ctx.arc(s.x+s.w/2,s.y+s.h/2,s.w/2,0,Math.PI*2);ctx.fill()}else{ctx.fillRect(s.x,s.y,s.w,s.h);ctx.fillRect(s.x-12,s.y+s.h*.35,s.w+24,4)}ctx.shadowBlur=0});if(boss)drawBoss(boss);drawRunner(ctx,p.x,p.y,p.invuln>0&&Math.floor(now/80)%2?"#fff":o.runner.color,p.face,p.h,p.attack>0);particles.forEach(q=>{ctx.globalAlpha=q.a;ctx.fillStyle=q.c;ctx.fillRect(q.x,q.y,6,6)});ctx.globalAlpha=1;drawHud(W,boss)}
 function drawDecor(d:Decor){const row=d.kind<4?0:2,col=d.kind<4?d.kind:d.kind-8;ctx.globalAlpha=.82;envSprite(col,row,d.x,d.y,d.w,d.h);ctx.globalAlpha=1}
 function drawPlatform(q:Platform){const floor=innerHeight-105;if(q.kind==="lift")envSprite(2,1,q.x-18,q.y-32,q.w+36,q.h+68);else if(q.kind==="bridge")envSprite(1,0,q.x-18,q.y-48,q.w+36,q.h+80);else{ctx.fillStyle="#14231b";ctx.fillRect(q.x,q.y,q.w,q.h+Math.max(22,floor-q.y-115));ctx.fillStyle=o.world.color;ctx.fillRect(q.x,q.y,q.w,7);for(let yy=12;yy<Math.min(145,floor-q.y);yy+=25)for(let i=7+(yy%2)*11;i<q.w;i+=32){ctx.fillStyle=yy%50?"#38543f":"#263d30";ctx.fillRect(q.x+i,q.y+yy,22,15)}}}
 function drawChaser(){const t=performance.now()/240;ctx.save();ctx.globalAlpha=.98;ctx.shadowBlur=48;ctx.shadowColor="#75ff47";ctx.translate(0,Math.sin(t)*5);sprite(0,1,chaser.x-70,chaser.y-62,chaser.w+140,chaser.h+82,false);ctx.shadowBlur=0;ctx.fillStyle="#07100de8";ctx.fillRect(Math.max(8,chaser.x+54),chaser.y-28,178,24);ctx.fillStyle="#ff536f";ctx.font="900 14px monospace";ctx.fillText("UNSTOPPABLE",Math.max(15,chaser.x+80),chaser.y-10);ctx.restore()}
 function drawRunner(c:CanvasRenderingContext2D,x:number,y:number,col:string,face:number,h:number,attacking=false){const moving=Math.abs(p.vx)>38,air=!p.grounded,walkFrame=moving?1+(Math.floor(performance.now()/115)%2):0,frameCol=attacking?3:air?2:walkFrame,bob=moving&&!air?Math.sin(performance.now()/115*Math.PI)*3:0,hue=[0,165,325,245][runnerIndex];c.save();c.filter=`hue-rotate(${hue}deg) saturate(${runnerIndex?1.2:1})`;c.shadowBlur=attacking?38:24;c.shadowColor=col;const dw=attacking?225:188,dh=attacking?205:198,dx=attacking?(face>0?x-48:x-112):x-60,dy=y+h-dh+bob;if(sprite(frameCol,0,dx,dy,dw,dh,face<0)){c.restore();return}c.restore();c.fillStyle=col;c.fillRect(x,y,66,h)}
 function drawEnemy(e:Enemy){const col=e.kind==="walker"?0:e.kind==="flyer"?1:2,t=performance.now()/150;ctx.save();ctx.translate(0,Math.sin(t+e.x*.03)*(e.kind==="flyer"?8:3));if(e.kind==="shooter"&&e.cool<.3){ctx.translate(Math.sign(e.vx)*-8,0);ctx.rotate(Math.sign(e.vx)*-.035)}if(e.hurt)ctx.globalAlpha=.45;ctx.shadowBlur=e.cool<.25?34:14;ctx.shadowColor=e.kind==="shooter"?"#ffb62e":o.world.color;if(sprite(col,1,e.x-48,e.y-72,e.w+96,e.h+108,e.vx<0)){ctx.restore();return}ctx.restore();ctx.fillStyle="#334b34";ctx.fillRect(e.x,e.y,e.w,e.h)}
 function drawPickup(q:Pickup,now:number){const col=q.kind==="gem"?0:q.kind==="heart"?1:2;if(sprite(col,3,q.x-13,q.y-13,q.w+26,q.h+26))return;ctx.fillStyle=q.kind==="gem"?"#d7ff53":q.kind==="heart"?"#ff536f":"#fff";ctx.fillRect(q.x,q.y,q.w,q.h)}
 function drawHazard(h:Hazard){if(h.kind==="spike"){if(!sprite(3,3,h.x-8,h.y-37,h.w+16,h.h+42)){ctx.fillStyle="#ff536f";ctx.fillRect(h.x,h.y,h.w,h.h)}}else if(h.kind==="mushroom"){envSprite(2,2,h.x-8,h.y-52,h.w+16,h.h+58)}else if(h.kind==="laser"){ctx.globalAlpha=.68+.3*Math.sin(performance.now()/80);envSprite(0,1,h.x-18,h.y-8,h.w+36,h.h+16);ctx.globalAlpha=1}else if(h.kind==="saw"){ctx.save();ctx.translate(h.x+h.w/2,h.y+h.h/2);ctx.rotate(performance.now()/230);envSprite(1,1,-h.w*.75,-h.h*.75,h.w*1.5,h.h*1.5);ctx.restore()}else{ctx.fillStyle="#000";ctx.fillRect(h.x,h.y,h.w,innerHeight-h.y)}}
 function drawBoss(b:NonNullable<typeof boss>){const t=performance.now()/180,charge=b.clock<.42;ctx.save();ctx.translate(b.x+b.w/2,b.y+b.h/2+Math.sin(t)*6);ctx.scale(charge?1.08:.98+Math.sin(t*.7)*.025,charge?.94:1);ctx.translate(-(b.x+b.w/2),-(b.y+b.h/2));if(charge)ctx.rotate(Math.sin(t*5)*.018);ctx.shadowBlur=charge?62:38;ctx.shadowColor=charge?"#fff":o.world.color;rosterSprite(bossIndex,1,b.x-82,b.y-68,b.w+164,b.h+105,true);ctx.restore();if(charge){ctx.globalAlpha=.82;envSprite(b.state===1?0:b.state===2?3:1,3,b.x-120,b.y+45,235,185);ctx.globalAlpha=1;burst(b.x+Math.random()*b.w,b.y+Math.random()*b.h,o.world.color,1)}ctx.shadowBlur=0;ctx.fillStyle="#07100b";ctx.fillRect(b.x,b.y-34,b.w,17);ctx.fillStyle=o.world.color;ctx.fillRect(b.x,b.y-34,b.w*(b.hp/b.max),17)}
 function drawHud(W:number,b:typeof boss){ctx.fillStyle="#070b14e8";ctx.fillRect(20,20,270,74);ctx.strokeStyle=o.world.color;ctx.lineWidth=4;ctx.strokeRect(20,20,270,74);ctx.fillStyle="#ff536f";ctx.font="25px monospace";ctx.fillText("♥".repeat(p.hp),42,63);ctx.fillStyle="#fff";ctx.font="700 16px monospace";ctx.fillText(`AXE ${p.ammo}`,185,64);ctx.fillText(`◆ ${gems}   ☠ ${kills}   ⚡ ${Math.floor(distance)}M`,W-330,50);if(elapsed<11000){ctx.fillStyle="#07101be8";ctx.fillRect(W/2-360,innerHeight-72,720,42);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.fillText("A/D MOVE · SPACE JUMP · LEFT CLICK ATTACK · RIGHT CLICK THROW · SHIFT DASH",W/2,innerHeight-45);ctx.textAlign="left"}if(b){ctx.fillStyle=o.world.color;ctx.fillText(`BOSS ${b.hp}/${b.max}`,W/2-45,38)}}
 function tick(now:number){if(stopped)return;const dt=Math.min((now-last)/1000,.034);last=now;elapsed+=dt*1000;update(dt,now);draw(now);if(!stopped)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);return cleanup;
}
