import {sfx,startMusic} from "./gameAudio";

export type ArcadeStats={score:number;distance:number;gems:number;rekt:number};
type World={id:string;color:string;sky:string;land:string};
type Runner={id:string;color:string};type Gear={id:string};
type Options={world:World;runner:Runner;gear:Gear;onStats:(s:ArcadeStats)=>void;onFinish:(s:ArcadeStats,durationMs:number)=>void};
type Rect={x:number;y:number;w:number;h:number};
type Enemy=Rect&{kind:"walker"|"flyer";hp:number;cool:number;vx:number;vy?:number;grounded?:boolean;jumpClock?:number;hurt?:number};
type Pickup=Rect&{kind:"gem"|"heart"|"ammo"};
type Shot=Rect&{vx:number;vy:number;enemy:boolean;kind?:"bolt"|"orb"|"wave"|"nova"|"fire"|"void";power?:number};
type Hazard=Rect&{kind:"spike"|"mushroom"|"pit"|"laser"|"saw";ttl?:number};
type Platform=Rect&{kind:"stone"|"bridge"|"lift";baseY:number;phase:number};
type Decor=Rect&{kind:0|1|2|3|8|9|10|11};
const hit=(a:Rect,b:Rect)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));

export function startArcadeGame(canvas:HTMLCanvasElement,keys:Set<string>,o:Options){
 const ctx=canvas.getContext("2d")!,sprites=new Image(),roster=new Image(),levelArt=new Image();sprites.src="/game-sprites.png";roster.src="/roster-bosses.png";levelArt.src="/level-atlas.png";startMusic();const runnerIndex=Math.max(0,["byte","nova","ember","void"].indexOf(o.runner.id)),bossIndex=Math.max(0,["base","forest","lava","cosmic"].indexOf(o.world.id));let stopped=false,frame=0,last=performance.now(),elapsed=0,lastHud=0,spawnClock=.8,pattern=0,camera=0,distance=0,gems=0,kills=0,bosses=0,nextBoss=520,shake=0,playerDeath=0,boss:null|{x:number;y:number;w:number;h:number;hp:number;max:number;state:number;clock:number;hurt:number} = null;
 const p={x:190,y:200,w:92,h:124,vx:0,vy:0,hp:5,maxHp:5,ammo:3,maxAmmo:15,grounded:false,lastGround:0,jumpQueued:-99,dash:0,dashCd:0,slide:0,attack:0,attackCd:0,invuln:0,face:1};
 const chaser={x:-255,y:0,w:270,h:300,speed:30};
 const was={jump:false,dash:false,melee:false,ranged:false};
 if(o.runner.id==="ember"||o.gear.id==="shield")p.hp=p.maxHp=7;
 const highJump=o.runner.id==="void"||o.gear.id==="boots",doubleGems=o.runner.id==="nova"||o.gear.id==="magnet";
 const kits={byte:{range:220,power:1,cool:.4},nova:{range:255,power:1,cool:.31},ember:{range:285,power:2,cool:.58},void:{range:335,power:3,cool:.68}} as const,kit=kits[o.runner.id as keyof typeof kits]||kits.byte,meleeRange=kit.range+(o.gear.id==="blade"?50:0);
 let enemies:Enemy[]=[],pickups:Pickup[]=[],shots:Shot[]=[],hazards:Hazard[]=[],platforms:Platform[]=[],decors:Decor[]=[],echoes:{x:number;y:number;a:number}[]=[],particles:{x:number;y:number;vx:number;vy:number;a:number;c:string}[]=[],deaths:{x:number;y:number;w:number;h:number;t:number;kind:"walker"|"flyer"|"boss";index:number}[]=[],pressed=new Set<string>();
 const resize=()=>{const d=Math.min(devicePixelRatio,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)},pointerDown=(e:PointerEvent)=>{if(e.button===0)pressed.add("melee");if(e.button===1)pressed.add("dash");if(e.button===2)pressed.add("ranged");e.preventDefault()},blockMenu=(e:Event)=>e.preventDefault();resize();canvas.style.cursor="crosshair";addEventListener("resize",resize);canvas.addEventListener("pointerdown",pointerDown);canvas.addEventListener("contextmenu",blockMenu);
 const burst=(x:number,y:number,c:string,n=9)=>{for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*240,vy:(Math.random()-.7)*220,a:1,c})};
 const sprite=(col:number,row:number,x:number,y:number,w:number,h:number,flip=false)=>{if(!sprites.complete||!sprites.naturalWidth)return false;const sw=sprites.naturalWidth/4,sh=sprites.naturalHeight/4;ctx.save();if(flip){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(sprites,col*sw,row*sh,sw,sh,0,0,w,h)}else ctx.drawImage(sprites,col*sw,row*sh,sw,sh,x,y,w,h);ctx.restore();return true};
 const rosterSprite=(col:number,row:number,x:number,y:number,w:number,h:number,flip=false)=>{if(!roster.complete||!roster.naturalWidth)return false;const sw=roster.naturalWidth/4,sh=roster.naturalHeight/4;ctx.save();if(flip){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(roster,col*sw,row*sh,sw,sh,0,0,w,h)}else ctx.drawImage(roster,col*sw,row*sh,sw,sh,x,y,w,h);ctx.restore();return true};
 const envSprite=(col:number,row:number,x:number,y:number,w:number,h:number)=>{if(!levelArt.complete||!levelArt.naturalWidth)return false;const sw=levelArt.naturalWidth/4,sh=levelArt.naturalHeight/4;ctx.drawImage(levelArt,col*sw,row*sh,sw,sh,x,y,w,h);return true};
 function spawnPattern(W:number,H:number,diff:number){const ground=H-105,roll=Math.floor(Math.random()*10),choice=roll===pattern?(roll+1+Math.floor(Math.random()*8))%10:roll,far=W+80,gap=140-diff*35;pattern=choice;if(Math.random()<.72){const kind=[0,1,2,3,8,9,10,11][Math.floor(Math.random()*8)] as Decor["kind"];decors.push({x:far+Math.random()*260,y:ground-(kind<4?235:150),w:kind<4?190:120,h:kind<4?220:140,kind})}
  if(choice===0){for(let i=0;i<3;i++)enemies.push({x:far+i*gap,y:ground-38,w:38,h:38,kind:"walker",hp:1,cool:0,vx:75+diff*80})}
  if(choice===1){enemies.push({x:far,y:ground-150,w:42,h:32,kind:"flyer",hp:1,cool:0,vx:95+diff*70});pickups.push({x:far+90,y:ground-175,w:18,h:18,kind:"gem"})}
  if(choice===2){hazards.push({x:far,y:ground-24,w:58,h:24,kind:"spike"});pickups.push({x:far+18,y:ground-105,w:18,h:18,kind:"gem"});pickups.push({x:far+58,y:ground-145,w:18,h:18,kind:"gem"})}
  if(choice===3){hazards.push({x:far,y:ground-25,w:65,h:25,kind:"mushroom"});enemies.push({x:far+175,y:ground-38,w:38,h:38,kind:"walker",hp:1,cool:0,vx:80})}
  if(choice===4){enemies.push({x:far,y:ground-82,w:78,h:82,kind:"walker",hp:2,cool:0,vx:55});pickups.push({x:far+190,y:ground-90,w:28,h:28,kind:"ammo"})}
  if(choice===5){hazards.push({x:far,y:ground,w:145,h:38,kind:"pit"});for(let i=0;i<3;i++)pickups.push({x:far+35+i*38,y:ground-105-Math.sin(i*Math.PI/2)*55,w:18,h:18,kind:"gem"})}
  if(choice===6){pickups.push({x:far,y:ground-85,w:22,h:22,kind:p.hp<p.maxHp/2?"heart":"gem"});enemies.push({x:far+130,y:ground-145,w:42,h:32,kind:"flyer",hp:1,cool:0,vx:100})}
  if(choice===7){for(let i=0;i<5;i++){const y=ground-145-(i%4)*125;platforms.push({x:far+i*330,y,w:310,h:58,kind:i===3?"lift":"stone",baseY:y,phase:Math.random()*6});pickups.push({x:far+135+i*330,y:y-58,w:28,h:28,kind:"gem"})}}
  if(choice===8){hazards.push({x:far,y:ground-285,w:120,h:285,kind:"laser"});platforms.push({x:far+240,y:ground-190,w:390,h:52,kind:"bridge",baseY:ground-190,phase:0});enemies.push({x:far+390,y:ground-280,w:86,h:90,kind:"walker",hp:2,cool:0,vx:65})}
  if(choice===9){hazards.push({x:far,y:ground-95,w:95,h:95,kind:"saw"});hazards.push({x:far+240,y:ground-34,w:125,h:34,kind:"spike"});platforms.push({x:far+420,y:ground-210,w:390,h:58,kind:"stone",baseY:ground-210,phase:0});platforms.push({x:far+850,y:ground-390,w:350,h:58,kind:"stone",baseY:ground-390,phase:0});enemies.push({x:far+540,y:ground-300,w:86,h:90,kind:Math.random()>.5?"walker":"flyer",hp:2,cool:0,vx:110})}
  if(Math.random()<.64){const blocks=3+Math.floor(Math.random()*3);for(let i=0;i<blocks;i++){const y=ground-145-i*118;platforms.push({x:far+650+i*245,y,w:265,h:54,kind:"stone",baseY:y,phase:0})}}
 }
 function killEnemy(e:Enemy){if(e.hp<=0)return;deaths.push({x:e.x,y:e.y,w:e.w,h:e.h,t:.72,kind:e.kind,index:0});e.hp=0;kills++;shake=9;sfx("hit");burst(e.x+e.w/2,e.y+e.h/2,"#fff",14);burst(e.x+e.w/2,e.y+e.h/2,o.world.color,24);if(Math.random()<.7)pickups.push({x:e.x,y:e.y,w:24,h:24,kind:"gem"})}
 function damage(n=1){if(p.invuln>0||playerDeath>0)return;p.hp-=n;p.invuln=2;shake=14;sfx("hurt");burst(p.x+p.w/2,p.y+p.h/2,"#fff",10);burst(p.x+p.w/2,p.y+p.h/2,"#ff476f",22);if(p.hp<=0){p.hp=0;playerDeath=1.05;p.vy=-420;p.vx=-p.face*180}}
 function finish(){if(stopped)return;stopped=true;const s={distance:Math.floor(distance),gems,kills,rekt:kills,score:Math.floor(distance+gems*120+kills*200)};o.onFinish(s,Math.floor(elapsed));cleanup()}
 function cleanup(){cancelAnimationFrame(frame);removeEventListener("resize",resize);canvas.removeEventListener("pointerdown",pointerDown);canvas.removeEventListener("contextmenu",blockMenu);canvas.style.cursor="";canvas.style.transform=""}
 function update(dt:number,now:number){const W=innerWidth,H=innerHeight,ground=H-105,diff=clamp(distance/2000,0,1),left=keys.has("KeyA")||keys.has("ArrowLeft"),right=keys.has("KeyD")||keys.has("ArrowRight"),down=keys.has("KeyS")||keys.has("ArrowDown"),jump=keys.has("Space")||keys.has("KeyW")||keys.has("ArrowUp"),dash=keys.has("ShiftLeft")||keys.has("ShiftRight"),melee=keys.has("KeyJ")||keys.has("KeyX"),ranged=keys.has("KeyK")||keys.has("KeyC"),jumpPressed=jump&&!was.jump,dashPressed=(dash&&!was.dash)||pressed.delete("dash"),meleePressed=(melee&&!was.melee)||pressed.delete("melee"),rangedPressed=(ranged&&!was.ranged)||pressed.delete("ranged");
  if(jumpPressed)p.jumpQueued=now;if((now-p.jumpQueued<250)&&(p.grounded||now-p.lastGround<200)){p.vy=highJump?-1080:-940;p.grounded=false;p.jumpQueued=-99}if(!jump&&p.vy<0)p.vy+=1080*dt;
  const dir=(right?1:0)-(left?1:0);if(dir)p.face=dir;const target=dir*(dash&&p.dashCd<=0?580:250);p.vx+=(target-p.vx)*Math.min(1,(p.grounded?10:5)*dt);if(!dir)p.vx*=Math.max(0,1-7*dt);
  if(dashPressed&&p.dashCd<=0){p.dash=.38;p.dashCd=1.1;p.vx=p.face*580;sfx("dash")}p.dash=Math.max(0,p.dash-dt);p.dashCd=Math.max(0,p.dashCd-dt);if(p.dash>0){echoes.push({x:p.x,y:p.y,a:.55});p.vx=p.face*580}
  if(down&&p.grounded&&Math.abs(p.vx)>90){p.slide=.55;p.h=68}else if(p.slide<=0){p.h=124}p.slide=Math.max(0,p.slide-dt);
  p.attackCd=Math.max(0,p.attackCd-dt);p.attack=Math.max(0,p.attack-dt);if(meleePressed&&p.attackCd<=0&&playerDeath<=0){p.attack=o.runner.id==="void"?.42:.28;p.attackCd=kit.cool;sfx("slash");if(o.runner.id==="void"){echoes.push({x:p.x,y:p.y,a:.9});p.x=clamp(p.x+p.face*85,70,W-360)}const ax=p.x+(p.face>0?p.w+meleeRange*.45:-meleeRange*.45);burst(ax,p.y+p.h*.48,"#fff",o.runner.id==="ember"?18:9);burst(ax,p.y+p.h*.48,o.runner.color,12+kit.power*7)}if(rangedPressed&&p.attackCd<=0&&p.ammo>0&&playerDeath<=0){p.ammo--;p.attackCd=o.runner.id==="void"?.8:.48;sfx("shot");const sx=p.x+(p.face>0?p.w:-40),sy=p.y+24;if(o.runner.id==="nova"){shots.push({x:sx,y:sy,w:42,h:18,vx:p.face*760,vy:-85,enemy:false,kind:"nova",power:1});shots.push({x:sx,y:sy+34,w:42,h:18,vx:p.face*760,vy:85,enemy:false,kind:"nova",power:1})}else if(o.runner.id==="ember")shots.push({x:sx,y:sy+25,w:125,h:62,vx:p.face*470,vy:0,enemy:false,kind:"fire",power:2});else if(o.runner.id==="void")shots.push({x:sx,y:sy,w:78,h:78,vx:p.face*690,vy:0,enemy:false,kind:"void",power:3});else shots.push({x:sx,y:sy,w:48,h:18,vx:p.face*620,vy:0,enemy:false,kind:"bolt",power:1})}
  const oldBottom=p.y+p.h;p.vy+=1280*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.x=clamp(p.x,70,W-360);
  const landing=platforms.find(q=>p.vy>=0&&p.x+p.w>q.x&&p.x<q.x+q.w&&oldBottom<=q.y+9&&p.y+p.h>=q.y);if(landing){p.y=landing.y-p.h;p.vy=0;p.grounded=true;p.lastGround=now}else{const underPit=hazards.some(h=>h.kind==="pit"&&p.x+p.w>h.x&&p.x<h.x+h.w);if(p.y+p.h>=ground&&!underPit){p.y=ground-p.h;p.vy=0;p.grounded=true;p.lastGround=now}else p.grounded=false}platforms.forEach(q=>{if(!hit(p,q)||p.grounded)return;if(p.vx>0&&p.x+p.w-q.x<38){p.x=q.x-p.w;p.vx=0}else if(p.vx<0&&q.x+q.w-p.x<38){p.x=q.x+q.w;p.vx=0}});if(p.y>H+80)damage(99);
  const cameraLine=W*.43,scroll=boss?0:Math.max(0,p.x-cameraLine)*5.2*dt;p.x-=scroll;camera+=scroll;distance+=scroll/10;p.invuln=Math.max(0,p.invuln-dt);
  if(!boss){chaser.y=ground-chaser.h;chaser.x+=chaser.speed*dt;chaser.x=Math.min(chaser.x,p.x-38)}
  if(!boss&&hit(p,chaser)){damage();p.vx=Math.max(p.vx,390);p.vy=-220;chaser.x-=145;shake=18}
  if(!boss&&distance>=nextBoss){bosses++;nextBoss+=620;boss={x:W+100,y:ground-285,w:245,h:285,hp:10+bosses*3,max:10+bosses*3,state:0,clock:2.4,hurt:0};sfx("boss");enemies=[];hazards=[];platforms=[];chaser.x=Math.min(chaser.x,p.x-220)}
  if(!boss){spawnClock-=dt;if(spawnClock<=0){spawnPattern(W,H,diff);spawnClock=Math.max(.72,1.8-diff*.75)}}
  [...enemies,...pickups,...hazards,...platforms,...decors].forEach(e=>e.x-=scroll);platforms.forEach(q=>{if(q.kind==="lift")q.y=q.baseY+Math.sin(now/650+q.phase)*58});shots.forEach(s=>{s.x+=(s.vx-(s.enemy?scroll*.16:scroll))*dt;s.y+=s.vy*dt});
  enemies.forEach(e=>{e.hurt=Math.max(0,(e.hurt||0)-dt);const dx=p.x-e.x;if(e.kind==="flyer"){e.vx+=(Math.sign(dx)*(125+diff*75)-e.vx)*dt*2.4;e.x+=e.vx*dt;e.y+=Math.sin(now/220+e.x/75)*72*dt+Math.sign(p.y-e.y)*28*dt}else{e.jumpClock=(e.jumpClock||Math.random()*1.4)-dt;const chase=Math.sign(dx)*(115+diff*80);e.vx+=(chase-e.vx)*Math.min(1,dt*5);e.x+=e.vx*dt;e.vy=(e.vy||0)+1280*dt;const old=e.y+e.h;e.y+=e.vy*dt;let floor=ground;for(const q of platforms)if(e.x+e.w>q.x&&e.x<q.x+q.w&&old<=q.y+10&&e.y+e.h>=q.y)floor=Math.min(floor,q.y);if(e.y+e.h>=floor){e.y=floor-e.h;e.vy=0;e.grounded=true;if((Math.abs(dx)>75&&(e.jumpClock||0)<=0)||platforms.some(q=>q.x<e.x+e.w+65&&q.x+q.w>e.x&&q.y<e.y+e.h-45)){e.vy=-760-Math.random()*100;e.grounded=false;e.jumpClock=.8+Math.random()*1.3}}else e.grounded=false}if(hit(p,e)){if(p.vy>120&&p.y+p.h<e.y+e.h*.55){killEnemy(e);p.vy=-600}else{damage();p.x+=Math.sign(p.x-e.x)*45;p.vx=Math.sign(p.x-e.x)*280}}});
  if(p.attack>0){const a={x:p.face>0?p.x+p.w-8:p.x-meleeRange+8,y:p.y+4,w:meleeRange,h:p.h-8};enemies.forEach(e=>{if(e.hp>0&&hit(a,e)){e.hurt=.2;if(e.hp<=kit.power)killEnemy(e);else{e.hp-=kit.power;shake=7;burst(e.x+e.w/2,e.y+e.h/2,o.runner.color,10)}}});if(boss&&hit(a,boss)){boss.hp-=kit.power;boss.hurt=.22;p.attack=0;p.x-=p.face*(o.runner.id==="void"?8:30);p.vx=-p.face*150;shake=12+kit.power*3;sfx("hit");burst(boss.x+18,boss.y+p.h*.7,"#fff",14+kit.power*5);burst(boss.x+18,boss.y+p.h*.7,o.runner.color,24+kit.power*10)}}
  pickups=pickups.filter(q=>{if(hit(p,q)){if(q.kind==="gem")gems+=doubleGems?2:1;if(q.kind==="heart")p.hp=Math.min(p.maxHp,p.hp+2);if(q.kind==="ammo")p.ammo=Math.min(p.maxAmmo,p.ammo+3);sfx("pickup");burst(q.x,q.y,q.kind==="heart"?"#ff48d7":q.kind==="ammo"?"#f7f7ff":"#65f8ff",6);return false}return q.x>-50});
  hazards.forEach(h=>{if(hit(p,h)){if(h.kind==="mushroom"){p.vy=-720;p.y=h.y-p.h-2}else if(h.kind==="spike"||h.kind==="laser"||h.kind==="saw")damage();else if(h.kind==="pit"&&p.grounded===false){/* fall naturally */}}});
  shots=shots.filter(s=>{if(s.enemy&&hit(p,s)){damage();burst(s.x,s.y,"#ff536f",14);return false}if(!s.enemy){const power=s.power||1,e=enemies.find(e=>e.hp>0&&hit(s,e));if(e){if(e.hp<=power)killEnemy(e);else{e.hp-=power;e.hurt=.25;burst(s.x,s.y,o.runner.color,14)}return s.kind==="nova"&&e.hp>0}if(boss&&hit(s,boss)){boss.hp-=power;boss.hurt=.22;shake=10+power*2;sfx("hit");burst(s.x,s.y,"#fff",14+power*4);burst(s.x,s.y,o.runner.color,18+power*7);return false}}return s.x>-160&&s.x<W+160});enemies=enemies.filter(e=>e.hp>0&&e.x>-100);hazards.forEach(h=>{if(h.ttl!==undefined)h.ttl-=dt});hazards=hazards.filter(h=>h.x>-200&&(h.ttl===undefined||h.ttl>0));platforms=platforms.filter(q=>q.x>-250);decors=decors.filter(q=>q.x>-300);
  if(boss){boss.x+=(W-350-boss.x)*Math.min(1,dt*2.2);boss.hurt=Math.max(0,boss.hurt-dt);boss.clock-=dt;if(boss.clock<=0){boss.state=(boss.state+1)%3;boss.clock=3.2+Math.random()*1.2;sfx("boss");if(bossIndex===0){if(boss.state===0)for(let i=0;i<3;i++)shots.push({x:boss.x,y:ground-35-i*42,w:46,h:22,vx:-330-i*55,vy:0,enemy:true,kind:"wave"});if(boss.state===1)for(let i=0;i<5;i++)shots.push({x:p.x-180+i*110,y:-40-i*25,w:28,h:52,vx:0,vy:340+i*20,enemy:true,kind:"bolt"});if(boss.state===2)hazards.push({x:p.x+110,y:ground-34,w:180,h:34,kind:"spike",ttl:1.7})}else if(bossIndex===1){if(boss.state===0)for(let i=0;i<3;i++)enemies.push({x:boss.x-80-i*105,y:ground-90,w:86,h:90,kind:"walker",hp:2,cool:0,vx:115});if(boss.state===1)for(let i=0;i<3;i++)hazards.push({x:p.x-80+i*145,y:ground-34,w:92,h:34,kind:"spike",ttl:1.7});if(boss.state===2)shots.push({x:boss.x,y:boss.y+100,w:60,h:60,vx:-250,vy:-320,enemy:true,kind:"orb"})}else if(bossIndex===2){if(boss.state===0)for(let i=0;i<6;i++)shots.push({x:boss.x,y:boss.y+80,w:32,h:32,vx:-240-i*34,vy:-330+i*105,enemy:true,kind:"orb"});if(boss.state===1)hazards.push({x:p.x+80,y:ground-210,w:95,h:210,kind:"laser",ttl:1.5});if(boss.state===2)for(let i=0;i<2;i++)shots.push({x:boss.x,y:ground-55-i*55,w:58,h:28,vx:-470-i*70,vy:0,enemy:true,kind:"wave"})}else{if(boss.state===0)for(let i=0;i<7;i++)shots.push({x:boss.x,y:boss.y+70,w:27,h:27,vx:-220-i*30,vy:-300+i*92,enemy:true,kind:"orb"});if(boss.state===1)for(let i=0;i<4;i++)shots.push({x:W*.25+i*W*.17,y:-50,w:34,h:34,vx:(i%2?1:-1)*80,vy:300,enemy:true,kind:"orb"});if(boss.state===2){shots.push({x:boss.x,y:boss.y+55,w:70,h:30,vx:-560,vy:0,enemy:true,kind:"wave"});shots.push({x:boss.x,y:boss.y+185,w:70,h:30,vx:-560,vy:0,enemy:true,kind:"wave"})}}}shots.forEach(s=>{if(s.enemy&&s.kind==="orb")s.vy+=360*dt});if(hit(p,boss)){damage(2);p.x=boss.x-p.w-8;p.vx=-390;p.vy=-250;shake=20}if(boss.hp<=0){deaths.push({x:boss.x,y:boss.y,w:boss.w,h:boss.h,t:1.35,kind:"boss",index:bossIndex});kills+=5;gems+=10;shake=28;sfx("boss");burst(boss.x+boss.w/2,boss.y+boss.h/2,"#fff",35);burst(boss.x+boss.w/2,boss.y+boss.h/2,o.world.color,55);boss=null;spawnClock=1.8}}
  echoes.forEach(e=>e.a-=dt*2.6);echoes=echoes.filter(e=>e.a>0);deaths.forEach(d=>{d.t-=dt;d.y-=35*dt});deaths=deaths.filter(d=>d.t>0);particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=450*dt;q.a-=dt*1.7});particles=particles.filter(q=>q.a>0);if(playerDeath>0){playerDeath-=dt;if(playerDeath<=0)finish()}shake=Math.max(0,shake-dt*28);canvas.style.transform=shake>0?`translate(${(Math.random()-.5)*shake}px,${(Math.random()-.5)*shake}px) scale(1.006)`:"";
  was.jump=jump;was.dash=dash;was.melee=melee;was.ranged=ranged;if(now-lastHud>90){lastHud=now;o.onStats({distance:Math.floor(distance),gems,rekt:kills,score:Math.floor(distance+gems*120+kills*200)})}
 }
 function draw(now:number){const W=innerWidth,H=innerHeight,ground=H-105,zone=Math.floor(camera/2300)%4,accent=[o.world.color,"#65dfff","#ff8a32","#bd5cff"][zone];ctx.fillStyle=["#061713","#07162d","#260d13","#120720"][zone];ctx.fillRect(0,0,W,H);
  ctx.globalAlpha=1;
  for(let i=0;i<85;i++){let sx=(i*173-camera*(i%4+1)*.035)%W;if(sx<0)sx+=W;const sy=(i*67)%(ground*.66);ctx.fillStyle=i%9===0?accent:"#dff8ee";ctx.globalAlpha=.35+(i%4)*.14;ctx.fillRect(sx,sy,i%11===0?4:2,i%11===0?4:2)}ctx.globalAlpha=1;
  const ridge=(speed:number,base:number,color:string,step:number)=>{ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,H);for(let x=-step;x<W+step;x+=step){const wx=x+camera*speed,peak=base-Math.sin(wx*.005)*55-Math.sin(wx*.014)*30;ctx.lineTo(x,peak)}ctx.lineTo(W,H);ctx.fill()};ridge(.08,ground-315,"#0b1830",185);ridge(.18,ground-230,"#102b2a",150);
  ctx.fillStyle="#142e29";for(let i=-2;i<13;i++){const rx=i*230-(camera*.27)%230,h=95+(i%4)*42;ctx.fillRect(rx,ground-160-h,70,h);ctx.fillRect(rx-18,ground-168-h,106,12);ctx.fillStyle=accent;ctx.globalAlpha=.22;ctx.fillRect(rx+28,ground-145-h,12,h-18);ctx.globalAlpha=1;ctx.fillStyle="#142e29"}
  ctx.strokeStyle=accent;ctx.globalAlpha=.38;ctx.lineWidth=3;for(let i=-2;i<12;i++){const vx=i*250-(camera*.34)%250;ctx.beginPath();ctx.moveTo(vx,-10);ctx.bezierCurveTo(vx+35,100,vx-25,170,vx+20,290);ctx.stroke();for(let y=65;y<260;y+=48){ctx.fillStyle=accent;ctx.fillRect(vx+Math.sin(y)*9,y,6,13)}}ctx.globalAlpha=1;
  ctx.fillStyle="#06130d";for(let i=-2;i<20;i++){const tx=i*125-(camera*.5)%125;ctx.fillRect(tx,ground-85,16,85);ctx.beginPath();ctx.moveTo(tx-45,ground-50);ctx.lineTo(tx+8,ground-170-(i%3)*18);ctx.lineTo(tx+56,ground-50);ctx.fill()}ctx.fillStyle=accent;ctx.fillRect(0,ground,W,8);ctx.fillStyle="#07150e";ctx.fillRect(0,ground+8,W,H-ground);ctx.fillStyle="#294b35";for(let g=-40;g<W;g+=42){ctx.fillRect(g-camera%42,ground+11,29,10);ctx.fillRect(g+10-camera%42,ground+27,19,9)}ctx.strokeStyle=accent;ctx.globalAlpha=.22;for(let g=0;g<W;g+=62){ctx.beginPath();ctx.moveTo(g-camera%62,ground);ctx.lineTo(g-camera%62,H);ctx.stroke()}ctx.globalAlpha=1;
  decors.forEach(drawDecor);drawChaser();platforms.forEach(drawPlatform);echoes.forEach(e=>{ctx.globalAlpha=e.a;drawRunner(ctx,e.x,e.y,o.runner.color,p.face,p.h,false)});ctx.globalAlpha=1;
  hazards.forEach(h=>drawHazard(h));pickups.forEach(q=>drawPickup(q,now));enemies.forEach(e=>drawEnemy(e));shots.forEach(drawShot);deaths.forEach(drawDeath);if(boss)drawBoss(boss);
  if(playerDeath>0){ctx.save();ctx.globalAlpha=clamp(playerDeath,0,1);ctx.translate(p.x+p.w/2,p.y+p.h/2);ctx.rotate((1-playerDeath)*1.35*p.face);ctx.translate(-(p.x+p.w/2),-(p.y+p.h/2));drawRunner(ctx,p.x,p.y,"#ff536f",p.face,p.h,false);ctx.restore()}else drawRunner(ctx,p.x,p.y,p.invuln>0&&Math.floor(now/80)%2?"#fff":o.runner.color,p.face,p.h,p.attack>0);
  particles.forEach(q=>{ctx.globalAlpha=q.a;ctx.fillStyle=q.c;ctx.fillRect(q.x,q.y,6,6)});ctx.globalAlpha=1;drawHud(W,boss)}
 function drawShot(s:Shot){const col=s.enemy?(s.kind==="orb"?"#b764ff":s.kind==="wave"?"#ff9a32":"#ff536f"):s.kind==="nova"?"#65f8ff":s.kind==="fire"?"#ff6b32":s.kind==="void"?"#ad7aff":o.runner.color;ctx.save();ctx.fillStyle=col;ctx.strokeStyle=col;ctx.shadowBlur=24;ctx.shadowColor=col;if(s.kind==="orb"||s.kind==="void"){ctx.beginPath();ctx.arc(s.x+s.w/2,s.y+s.h/2,s.w/2,0,Math.PI*2);ctx.fill();if(s.kind==="void"){ctx.globalAlpha=.45;ctx.lineWidth=6;ctx.beginPath();ctx.arc(s.x+s.w/2,s.y+s.h/2,s.w*.72,0,Math.PI*2);ctx.stroke()}}else if(s.kind==="fire"){ctx.beginPath();ctx.moveTo(s.x,s.y+s.h/2);ctx.quadraticCurveTo(s.x+s.w*.55,s.y-28,s.x+s.w,s.y+s.h/2);ctx.quadraticCurveTo(s.x+s.w*.48,s.y+s.h+28,s.x,s.y+s.h/2);ctx.fill()}else if(s.kind==="nova"){ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(s.x,s.y+s.h);ctx.lineTo(s.x+s.w*.45,s.y);ctx.lineTo(s.x+s.w,s.y+s.h*.5);ctx.stroke()}else if(!s.enemy){ctx.beginPath();ctx.moveTo(s.x,s.y+s.h/2);ctx.lineTo(s.x+s.w*.72,s.y);ctx.lineTo(s.x+s.w,s.y+s.h/2);ctx.lineTo(s.x+s.w*.72,s.y+s.h);ctx.closePath();ctx.fill()}else{ctx.fillRect(s.x,s.y,s.w,s.h)}ctx.restore()}
 function drawDecor(d:Decor){const row=d.kind<4?0:2,col=d.kind<4?d.kind:d.kind-8;ctx.globalAlpha=.82;envSprite(col,row,d.x,d.y,d.w,d.h);ctx.globalAlpha=1}
 function drawPlatform(q:Platform){const floor=innerHeight-105;if(q.kind==="lift")envSprite(2,1,q.x-18,q.y-32,q.w+36,q.h+68);else if(q.kind==="bridge")envSprite(1,0,q.x-18,q.y-48,q.w+36,q.h+80);else{ctx.fillStyle="#14231b";ctx.fillRect(q.x,q.y,q.w,q.h+Math.max(22,floor-q.y-115));ctx.fillStyle=o.world.color;ctx.fillRect(q.x,q.y,q.w,7);for(let yy=12;yy<Math.min(145,floor-q.y);yy+=25)for(let i=7+(yy%2)*11;i<q.w;i+=32){ctx.fillStyle=yy%50?"#38543f":"#263d30";ctx.fillRect(q.x+i,q.y+yy,22,15)}}}
 function drawChaser(){if(boss)return;const t=performance.now()/240,x=chaser.x,y=chaser.y;ctx.save();ctx.translate(0,Math.sin(t)*7);ctx.shadowBlur=45;ctx.shadowColor="#d340ff";ctx.fillStyle="#68128f";ctx.beginPath();ctx.ellipse(x+135,y+98,128,112,0,Math.PI,Math.PI*2);ctx.lineTo(x+250,y+188);ctx.quadraticCurveTo(x+135,y+235,x+20,y+188);ctx.closePath();ctx.fill();ctx.fillStyle="#b84ee8";ctx.beginPath();ctx.ellipse(x+135,y+92,92,78,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#f5f0ff";ctx.fillRect(x+82,y+85,34,42);ctx.fillRect(x+156,y+85,34,42);ctx.fillStyle="#17051f";ctx.fillRect(x+96,y+94,13,27);ctx.fillRect(x+163,y+94,13,27);ctx.lineWidth=25;ctx.lineCap="round";for(let i=0;i<6;i++){ctx.strokeStyle=i%2?"#8d27bd":"#5c0e82";ctx.beginPath();ctx.moveTo(x+35+i*40,y+175);ctx.quadraticCurveTo(x+10+i*52,y+230+Math.sin(t+i)*25,x-18+i*57,y+292);ctx.stroke()}ctx.fillStyle="#12051ae8";ctx.fillRect(Math.max(8,x+45),y-30,205,25);ctx.fillStyle="#ff65ef";ctx.font="900 14px monospace";ctx.fillText("ABYSSAL PURSUER",Math.max(15,x+64),y-12);ctx.restore()}
 function drawRunner(c:CanvasRenderingContext2D,x:number,y:number,col:string,face:number,h:number,attacking=false){const moving=Math.abs(p.vx)>38,air=!p.grounded,walkFrame=moving?1+(Math.floor(performance.now()/115)%2):0,frameCol=attacking?3:air?2:walkFrame,bob=moving&&!air?Math.sin(performance.now()/115*Math.PI)*4:0,hue=[0,165,325,245][runnerIndex];c.save();c.filter=`hue-rotate(${hue}deg) saturate(${runnerIndex?1.2:1})`;c.shadowBlur=attacking?46:28;c.shadowColor=col;const dw=attacking?465:400,dh=attacking?430:420,dx=attacking?(face>0?x-112:x-250):x-150,feetOffset=dh*.145,dy=y+h-dh+feetOffset+bob;if(sprite(frameCol,0,dx,dy,dw,dh,face<0)){c.restore()}else{c.restore();c.fillStyle=col;c.fillRect(x,y,92,h)}if(attacking){c.save();c.translate(face>0?x+p.w:x,y+h*.48);c.scale(face,1);c.strokeStyle=col;c.fillStyle=col;c.shadowBlur=35;c.shadowColor=col;c.lineCap="round";if(o.runner.id==="byte"){c.lineWidth=15;c.beginPath();c.arc(0,0,135,-1.05,1.05);c.stroke()}else if(o.runner.id==="nova"){c.lineWidth=9;for(let i=0;i<2;i++){c.beginPath();c.arc(15,i?22:-22,170-i*20,-.9,.9);c.stroke()}}else if(o.runner.id==="ember"){c.globalAlpha=.8;c.beginPath();c.moveTo(5,-75);c.quadraticCurveTo(245,0,10,85);c.quadraticCurveTo(95,0,5,-75);c.fill()}else{c.lineWidth=18;for(let i=0;i<3;i++){c.globalAlpha=1-i*.24;c.beginPath();c.moveTo(20+i*22,-82);c.lineTo(305-i*25,0);c.lineTo(20+i*22,82);c.stroke()}}c.restore()}}
 function drawEnemy(e:Enemy){const col=e.kind==="walker"?0:1,t=performance.now()/150;ctx.save();ctx.translate(0,e.kind==="flyer"?Math.sin(t+e.x*.03)*9:0);if(e.hurt)ctx.globalAlpha=.45;ctx.shadowBlur=22;ctx.shadowColor=o.world.color;const dw=e.kind==="walker"?320:270,dh=e.kind==="walker"?330:280,dx=e.x-(dw-e.w)/2,feetOffset=e.kind==="walker"?dh*.22:0,dy=e.y+e.h-dh+feetOffset;if(sprite(col,1,dx,dy,dw,dh,e.vx<0)){ctx.restore();return}ctx.restore();ctx.fillStyle="#334b34";ctx.fillRect(e.x,e.y,e.w,e.h)}
 function drawPickup(q:Pickup,now:number){const col=q.kind==="gem"?0:q.kind==="heart"?1:2;if(sprite(col,3,q.x-13,q.y-13,q.w+26,q.h+26))return;ctx.fillStyle=q.kind==="gem"?"#d7ff53":q.kind==="heart"?"#ff536f":"#fff";ctx.fillRect(q.x,q.y,q.w,q.h)}
 function drawHazard(h:Hazard){if(h.kind==="spike"){if(!sprite(3,3,h.x-8,h.y-37,h.w+16,h.h+42)){ctx.fillStyle="#ff536f";ctx.fillRect(h.x,h.y,h.w,h.h)}}else if(h.kind==="mushroom"){envSprite(2,2,h.x-8,h.y-52,h.w+16,h.h+58)}else if(h.kind==="laser"){ctx.globalAlpha=.68+.3*Math.sin(performance.now()/80);envSprite(0,1,h.x-18,h.y-8,h.w+36,h.h+16);ctx.globalAlpha=1}else if(h.kind==="saw"){ctx.save();ctx.translate(h.x+h.w/2,h.y+h.h/2);ctx.rotate(performance.now()/230);envSprite(1,1,-h.w*.75,-h.h*.75,h.w*1.5,h.h*1.5);ctx.restore()}else{ctx.fillStyle="#000";ctx.fillRect(h.x,h.y,h.w,innerHeight-h.y)}}
 function drawDeath(d:(typeof deaths)[number]){ctx.save();const a=clamp(d.t/(d.kind==="boss"?1.35:.72),0,1);ctx.globalAlpha=a;ctx.translate(d.x+d.w/2,d.y+d.h/2);ctx.rotate((1-a)*(d.kind==="boss"?1.1:1.7));ctx.scale(1+(1-a)*.35,a);ctx.translate(-(d.x+d.w/2),-(d.y+d.h/2));ctx.filter="brightness(2) saturate(.4)";if(d.kind==="boss")rosterSprite(d.index,1,d.x-82,d.y-68,d.w+164,d.h+105,true);else{const col=d.kind==="walker"?0:1;sprite(col,1,d.x-110,d.y-180,d.w+220,d.h+230,false)}ctx.restore()}
 function drawBoss(b:NonNullable<typeof boss>){const t=performance.now()/180,charge=b.clock<.75;ctx.save();ctx.translate(b.x+b.w/2,b.y+b.h/2+Math.sin(t)*6);ctx.scale(charge?1.08:.98+Math.sin(t*.7)*.025,charge?.94:1);ctx.translate(-(b.x+b.w/2),-(b.y+b.h/2));if(charge)ctx.rotate(Math.sin(t*5)*.018);ctx.globalAlpha=b.hurt>0&&Math.floor(performance.now()/45)%2?.35:1;ctx.filter=b.hurt>0?"brightness(3) saturate(0)":"none";ctx.shadowBlur=charge?62:38;ctx.shadowColor=charge?"#fff":o.world.color;rosterSprite(bossIndex,1,b.x-82,b.y-68,b.w+164,b.h+105,true);ctx.restore();if(charge){ctx.globalAlpha=.82;envSprite(b.state===1?0:b.state===2?3:1,3,b.x-120,b.y+45,235,185);ctx.globalAlpha=1;burst(b.x+Math.random()*b.w,b.y+Math.random()*b.h,o.world.color,1)}ctx.shadowBlur=0;ctx.fillStyle="#07100b";ctx.fillRect(b.x,b.y-34,b.w,17);ctx.fillStyle=o.world.color;ctx.fillRect(b.x,b.y-34,b.w*(b.hp/b.max),17)}
 function drawHud(W:number,b:typeof boss){ctx.fillStyle="#070b14e8";ctx.fillRect(20,20,270,74);ctx.strokeStyle=o.world.color;ctx.lineWidth=4;ctx.strokeRect(20,20,270,74);ctx.fillStyle="#ff536f";ctx.font="25px monospace";ctx.fillText("♥".repeat(p.hp),42,63);ctx.fillStyle="#fff";ctx.font="700 16px monospace";ctx.fillText(`AXE ${p.ammo}`,185,64);ctx.fillText(`◆ ${gems}   ☠ ${kills}   ⚡ ${Math.floor(distance)}M`,W-330,50);if(elapsed<11000){ctx.fillStyle="#07101be8";ctx.fillRect(W/2-360,innerHeight-72,720,42);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.fillText("A/D MOVE · SPACE JUMP · LEFT CLICK ATTACK · RIGHT CLICK THROW · SHIFT DASH",W/2,innerHeight-45);ctx.textAlign="left"}if(b){ctx.fillStyle=o.world.color;ctx.fillText(`BOSS ${b.hp}/${b.max}`,W/2-45,38)}}
 function tick(now:number){if(stopped)return;if(!sprites.naturalWidth||!roster.naturalWidth||!levelArt.naturalWidth){ctx.fillStyle="#04100c";ctx.fillRect(0,0,innerWidth,innerHeight);ctx.fillStyle=o.world.color;ctx.font="900 18px monospace";ctx.textAlign="center";ctx.fillText("LOADING RUN ASSETS...",innerWidth/2,innerHeight/2);ctx.textAlign="left";last=now;frame=requestAnimationFrame(tick);return}const dt=Math.min((now-last)/1000,.034);last=now;elapsed+=dt*1000;update(dt,now);draw(now);if(!stopped)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);return cleanup;
}
