export type ArcadeStats={score:number;distance:number;gems:number;rekt:number};
type World={id:string;color:string;sky:string;land:string};
type Runner={id:string;color:string};type Gear={id:string};
type Options={world:World;runner:Runner;gear:Gear;onStats:(s:ArcadeStats)=>void;onFinish:(s:ArcadeStats,durationMs:number)=>void};
type Rect={x:number;y:number;w:number;h:number};
type Enemy=Rect&{kind:"walker"|"flyer"|"shooter";hp:number;cool:number;vx:number};
type Pickup=Rect&{kind:"gem"|"heart"|"ammo"};
type Shot=Rect&{vx:number;vy:number;enemy:boolean};
type Hazard=Rect&{kind:"spike"|"mushroom"|"pit"};
const hit=(a:Rect,b:Rect)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));

export function startArcadeGame(canvas:HTMLCanvasElement,keys:Set<string>,o:Options){
 const ctx=canvas.getContext("2d")!;let stopped=false,frame=0,last=performance.now(),elapsed=0,lastHud=0,spawnClock=.8,pattern=0,camera=0,distance=0,gems=0,kills=0,bosses=0,nextBoss=400,boss:null|{x:number;y:number;w:number;h:number;hp:number;max:number;state:number;clock:number} = null;
 const p={x:130,y:200,w:42,h:54,vx:0,vy:0,hp:5,maxHp:5,ammo:3,maxAmmo:15,grounded:false,lastGround:0,jumpQueued:-99,dash:0,dashCd:0,slide:0,attack:0,attackCd:0,invuln:0,face:1};
 const was={jump:false,dash:false,melee:false,ranged:false};
 if(o.runner.id==="ember"||o.gear.id==="shield")p.hp=p.maxHp=7;
 const highJump=o.runner.id==="void"||o.gear.id==="boots",doubleGems=o.runner.id==="nova"||o.gear.id==="magnet";
 let enemies:Enemy[]=[],pickups:Pickup[]=[],shots:Shot[]=[],hazards:Hazard[]=[],echoes:{x:number;y:number;a:number}[]=[],particles:{x:number;y:number;vx:number;vy:number;a:number;c:string}[]=[];
 const resize=()=>{const d=Math.min(devicePixelRatio,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)};resize();addEventListener("resize",resize);
 const burst=(x:number,y:number,c:string,n=9)=>{for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*240,vy:(Math.random()-.7)*220,a:1,c})};
 function spawnPattern(W:number,H:number,diff:number){const ground=H-105,choice=pattern++%7,far=W+80,gap=140-diff*35;
  if(choice===0){for(let i=0;i<3;i++)enemies.push({x:far+i*gap,y:ground-38,w:38,h:38,kind:"walker",hp:1,cool:0,vx:75+diff*80})}
  if(choice===1){enemies.push({x:far,y:ground-150,w:42,h:32,kind:"flyer",hp:1,cool:0,vx:95+diff*70});pickups.push({x:far+90,y:ground-175,w:18,h:18,kind:"gem"})}
  if(choice===2){hazards.push({x:far,y:ground-24,w:58,h:24,kind:"spike"});pickups.push({x:far+18,y:ground-105,w:18,h:18,kind:"gem"});pickups.push({x:far+58,y:ground-145,w:18,h:18,kind:"gem"})}
  if(choice===3){hazards.push({x:far,y:ground-25,w:65,h:25,kind:"mushroom"});enemies.push({x:far+175,y:ground-38,w:38,h:38,kind:"walker",hp:1,cool:0,vx:80})}
  if(choice===4){enemies.push({x:far,y:ground-46,w:44,h:46,kind:"shooter",hp:1,cool:.7,vx:35});pickups.push({x:far+140,y:ground-65,w:22,h:22,kind:"ammo"})}
  if(choice===5){hazards.push({x:far,y:ground,w:145,h:38,kind:"pit"});for(let i=0;i<3;i++)pickups.push({x:far+35+i*38,y:ground-105-Math.sin(i*Math.PI/2)*55,w:18,h:18,kind:"gem"})}
  if(choice===6){pickups.push({x:far,y:ground-85,w:22,h:22,kind:p.hp<p.maxHp/2?"heart":"gem"});enemies.push({x:far+130,y:ground-145,w:42,h:32,kind:"flyer",hp:1,cool:0,vx:100})}
 }
 function killEnemy(e:Enemy){e.hp=0;kills++;burst(e.x+e.w/2,e.y+e.h/2,o.world.color);if(Math.random()<.7)pickups.push({x:e.x,y:e.y,w:18,h:18,kind:"gem"})}
 function damage(n=1){if(p.invuln>0)return;p.hp-=n;p.invuln=2;burst(p.x+p.w/2,p.y+p.h/2,"#ff476f",12);if(p.hp<=0)finish()}
 function finish(){if(stopped)return;stopped=true;const s={distance:Math.floor(distance),gems,kills,rekt:kills,score:Math.floor(distance+gems*120+kills*200)};o.onFinish(s,Math.floor(elapsed));cleanup()}
 function cleanup(){cancelAnimationFrame(frame);removeEventListener("resize",resize)}
 function update(dt:number,now:number){const W=innerWidth,H=innerHeight,ground=H-105,diff=clamp(distance/2000,0,1),left=keys.has("KeyA")||keys.has("ArrowLeft"),right=keys.has("KeyD")||keys.has("ArrowRight"),down=keys.has("KeyS")||keys.has("ArrowDown"),jump=keys.has("Space")||keys.has("KeyW")||keys.has("ArrowUp"),dash=keys.has("ShiftLeft")||keys.has("ShiftRight"),melee=keys.has("KeyJ")||keys.has("KeyX"),ranged=keys.has("KeyK")||keys.has("KeyC"),jumpPressed=jump&&!was.jump,dashPressed=dash&&!was.dash,meleePressed=melee&&!was.melee,rangedPressed=ranged&&!was.ranged;
  if(jumpPressed)p.jumpQueued=now;if((now-p.jumpQueued<250)&&(p.grounded||now-p.lastGround<200)){p.vy=highJump?-650:-585;p.grounded=false;p.jumpQueued=-99}if(!jump&&p.vy<0)p.vy+=1450*dt;
  const dir=(right?1:0)-(left?1:0);if(dir)p.face=dir;const target=dir*(dash&&p.dashCd<=0?580:250);p.vx+=(target-p.vx)*Math.min(1,(p.grounded?10:5)*dt);if(!dir)p.vx*=Math.max(0,1-7*dt);
  if(dashPressed&&p.dashCd<=0){p.dash=.38;p.dashCd=1.1;p.vx=p.face*580}p.dash=Math.max(0,p.dash-dt);p.dashCd=Math.max(0,p.dashCd-dt);if(p.dash>0){echoes.push({x:p.x,y:p.y,a:.55});p.vx=p.face*580}
  if(down&&p.grounded&&Math.abs(p.vx)>90){p.slide=.55;p.h=30}else if(p.slide<=0){p.h=54}p.slide=Math.max(0,p.slide-dt);
  p.attackCd=Math.max(0,p.attackCd-dt);p.attack=Math.max(0,p.attack-dt);if(meleePressed&&p.attackCd<=0){p.attack=.2;p.attackCd=.36}if(rangedPressed&&p.attackCd<=0&&p.ammo>0){p.ammo--;p.attackCd=.45;shots.push({x:p.x+(p.face>0?p.w:-18),y:p.y+19,w:18,h:8,vx:p.face*620,vy:0,enemy:false})}
  p.vy+=1450*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.x=clamp(p.x,45,W-260);
  const underPit=hazards.some(h=>h.kind==="pit"&&p.x+p.w>h.x&&p.x<h.x+h.w);if(p.y+p.h>=ground&&!underPit){p.y=ground-p.h;p.vy=0;p.grounded=true;p.lastGround=now}else p.grounded=false;if(p.y>H+80)damage(99);
  const scroll=Math.max(120,p.vx+185)*dt;camera+=scroll;distance+=scroll/10;p.invuln=Math.max(0,p.invuln-dt);
  if(!boss&&distance>=nextBoss){bosses++;nextBoss+=400;boss={x:W+100,y:ground-190,w:150,h:190,hp:8+bosses*2,max:8+bosses*2,state:0,clock:1.2};enemies=[];hazards=[]}
  if(!boss){spawnClock-=dt;if(spawnClock<=0){spawnPattern(W,H,diff);spawnClock=Math.max(.72,1.8-diff*.75)}}
  [...enemies,...pickups,...hazards].forEach(e=>e.x-=scroll);shots.forEach(s=>{s.x+=(s.vx-scroll)*dt;s.y+=s.vy*dt});
  enemies.forEach(e=>{e.x-=e.vx*dt*(e.kind==="flyer"?.6:1);if(e.kind==="flyer")e.y+=Math.sin(now/280+e.x/90)*55*dt;if(e.kind==="shooter"){e.cool-=dt;if(e.cool<=0){e.cool=Math.max(.7,1.5-diff*.5);shots.push({x:e.x,y:e.y+15,w:13,h:9,vx:-260-diff*120,vy:0,enemy:true})}}if(hit(p,e)){if(p.vy>120&&p.y+p.h<e.y+e.h*.55){killEnemy(e);p.vy=-480}else damage()}});
  if(p.attack>0){const a={x:p.face>0?p.x+p.w:p.x-95,y:p.y-8,w:95,h:p.h+16};enemies.forEach(e=>{if(e.hp>0&&hit(a,e))killEnemy(e)});if(boss&&hit(a,boss)){boss.hp--;p.attack=0;burst(boss.x,boss.y,o.world.color,5)}}
  pickups=pickups.filter(q=>{if(hit(p,q)){if(q.kind==="gem")gems+=doubleGems?2:1;if(q.kind==="heart")p.hp=Math.min(p.maxHp,p.hp+2);if(q.kind==="ammo")p.ammo=Math.min(p.maxAmmo,p.ammo+3);burst(q.x,q.y,q.kind==="heart"?"#ff48d7":q.kind==="ammo"?"#f7f7ff":"#65f8ff",6);return false}return q.x>-50});
  hazards.forEach(h=>{if(hit(p,h)){if(h.kind==="mushroom"){p.vy=-720;p.y=h.y-p.h-2}else if(h.kind==="spike")damage();else if(h.kind==="pit"&&p.grounded===false){/* fall naturally */}}});
  shots=shots.filter(s=>{if(s.enemy&&hit(p,s)){damage();return false}if(!s.enemy){const e=enemies.find(e=>e.hp>0&&hit(s,e));if(e){killEnemy(e);return false}if(boss&&hit(s,boss)){boss.hp--;burst(s.x,s.y,o.world.color,4);return false}}return s.x>-30&&s.x<W+30});enemies=enemies.filter(e=>e.hp>0&&e.x>-100);hazards=hazards.filter(h=>h.x>-200);
  if(boss){boss.x+=(W-250-boss.x)*Math.min(1,dt*2.2);boss.clock-=dt;if(boss.clock<=0){boss.state=(boss.state+1)%3;boss.clock=Math.max(.7,1.7-diff*.5);if(boss.state===0)shots.push({x:boss.x,y:boss.y+70,w:24,h:18,vx:-360,vy:0,enemy:true});if(boss.state===1)for(let i=0;i<3;i++)shots.push({x:boss.x,y:boss.y+40,w:18,h:18,vx:-250-i*35,vy:-160+i*100,enemy:true});if(boss.state===2)enemies.push({x:boss.x-20,y:ground-38,w:38,h:38,kind:"walker",hp:1,cool:0,vx:120})}shots.forEach(s=>{if(s.enemy)s.vy+=260*dt});if(hit(p,boss))damage(2);if(boss.hp<=0){kills+=5;gems+=10;burst(boss.x+70,boss.y+90,o.world.color,35);boss=null;spawnClock=1.6}}
  echoes.forEach(e=>e.a-=dt*2.6);echoes=echoes.filter(e=>e.a>0);particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=450*dt;q.a-=dt*1.7});particles=particles.filter(q=>q.a>0);
  was.jump=jump;was.dash=dash;was.melee=melee;was.ranged=ranged;if(now-lastHud>90){lastHud=now;o.onStats({distance:Math.floor(distance),gems,rekt:kills,score:Math.floor(distance+gems*120+kills*200)})}
 }
 function draw(now:number){const W=innerWidth,H=innerHeight,ground=H-105;ctx.fillStyle=o.world.sky;ctx.fillRect(0,0,W,H);ctx.fillStyle="#fff";for(let i=0;i<80;i++){const sx=(i*157-camera*(i%3+1)*.08)%W,sy=(i*83)%(ground*.62);ctx.fillRect(sx,sy,i%9?1:3,i%9?1:3)}ctx.fillStyle=o.world.land;for(let i=0;i<8;i++){const bx=i*300-(camera*.16)%300;ctx.beginPath();ctx.moveTo(bx,ground);ctx.lineTo(bx+145,ground-170-(i%3)*45);ctx.lineTo(bx+300,ground);ctx.fill()}ctx.fillStyle="#07101b";for(let i=0;i<17;i++){const tx=i*120-(camera*.4)%120;ctx.fillRect(tx,ground-90,14,90);ctx.beginPath();ctx.moveTo(tx-32,ground-55);ctx.lineTo(tx+7,ground-145);ctx.lineTo(tx+48,ground-55);ctx.fill()}ctx.fillStyle=o.world.color;ctx.fillRect(0,ground,W,6);ctx.fillStyle="#0b1420";ctx.fillRect(0,ground+6,W,H-ground);ctx.strokeStyle=o.world.color;ctx.globalAlpha=.22;for(let g=0;g<W;g+=55){ctx.beginPath();ctx.moveTo(g-camera%55,ground);ctx.lineTo(g-camera%55,H);ctx.stroke()}ctx.globalAlpha=1;
  echoes.forEach(e=>{ctx.globalAlpha=e.a;drawRunner(ctx,e.x,e.y,o.runner.color,p.face,p.h)});ctx.globalAlpha=1;hazards.forEach(h=>drawHazard(h));pickups.forEach(q=>drawPickup(q,now));enemies.forEach(e=>drawEnemy(e));shots.forEach(s=>{ctx.fillStyle=s.enemy?"#ff536f":"#f7f7ff";ctx.fillRect(s.x,s.y,s.w,s.h)});if(boss)drawBoss(boss);drawRunner(ctx,p.x,p.y,p.invuln>0&&Math.floor(now/80)%2?"#fff":o.runner.color,p.face,p.h);if(p.attack>0){ctx.strokeStyle="#fff";ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x+(p.face>0?60:-18),p.y+25,42,p.face>0?-1.2:2, p.face>0?1.2:4.2);ctx.stroke()}particles.forEach(q=>{ctx.globalAlpha=q.a;ctx.fillStyle=q.c;ctx.fillRect(q.x,q.y,5,5)});ctx.globalAlpha=1;drawHud(W,boss)}
 function drawRunner(c:CanvasRenderingContext2D,x:number,y:number,col:string,face:number,h:number){c.fillStyle=col;c.fillRect(x+5,y,32,18);c.fillRect(x,y+18,42,h-18);c.fillStyle="#07110d";c.fillRect(x+(face>0?27:9),y+7,6,6);c.fillStyle="#fff";c.fillRect(x+7,y+24,8,5)}
 function drawEnemy(e:Enemy){ctx.fillStyle=e.kind==="flyer"?"#1b1730":"#131018";ctx.fillRect(e.x,e.y,e.w,e.h);ctx.strokeStyle=o.world.color;ctx.lineWidth=3;ctx.strokeRect(e.x,e.y,e.w,e.h);ctx.fillStyle=o.world.color;ctx.fillRect(e.x+7,e.y+9,6,6);ctx.fillRect(e.x+e.w-13,e.y+9,6,6);if(e.kind==="shooter")ctx.fillRect(e.x-12,e.y+18,14,8)}
 function drawPickup(q:Pickup,now:number){ctx.save();ctx.translate(q.x+q.w/2,q.y+q.h/2);if(q.kind==="gem")ctx.rotate(now/400);ctx.fillStyle=q.kind==="gem"?"#65f8ff":q.kind==="heart"?"#ff48d7":"#f5f5ff";if(q.kind==="heart"){ctx.font="25px monospace";ctx.fillText("♥",-10,10)}else ctx.fillRect(-q.w/2,-q.h/2,q.w,q.h);ctx.restore()}
 function drawHazard(h:Hazard){if(h.kind==="spike"){ctx.fillStyle="#ff536f";for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(h.x+i*20,h.y+h.h);ctx.lineTo(h.x+10+i*20,h.y);ctx.lineTo(h.x+20+i*20,h.y+h.h);ctx.fill()}}else if(h.kind==="mushroom"){ctx.fillStyle="#b04cff";ctx.fillRect(h.x+20,h.y+10,25,18);ctx.beginPath();ctx.arc(h.x+32,h.y+8,32,Math.PI,0);ctx.fill()}else{ctx.fillStyle="#000";ctx.fillRect(h.x,h.y,h.w,innerHeight-h.y)}}
 function drawBoss(b:NonNullable<typeof boss>){ctx.shadowBlur=28;ctx.shadowColor=o.world.color;ctx.fillStyle="#10121a";ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeStyle=o.world.color;ctx.lineWidth=7;ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.fillStyle=o.world.color;ctx.fillRect(b.x+30,b.y+42,28,20);ctx.fillRect(b.x+92,b.y+42,28,20);ctx.fillRect(b.x+40,b.y+120,70,18);ctx.shadowBlur=0;ctx.fillStyle="#070b12";ctx.fillRect(b.x,b.y-30,b.w,14);ctx.fillStyle=o.world.color;ctx.fillRect(b.x,b.y-30,b.w*(b.hp/b.max),14)}
 function drawHud(W:number,b:typeof boss){ctx.fillStyle="#070b14e8";ctx.fillRect(20,20,270,74);ctx.strokeStyle=o.world.color;ctx.lineWidth=4;ctx.strokeRect(20,20,270,74);ctx.fillStyle="#ff48d7";ctx.font="25px monospace";ctx.fillText("♥".repeat(p.hp),42,63);ctx.fillStyle="#fff";ctx.font="700 16px monospace";ctx.fillText(`AXE ${p.ammo}`,185,64);ctx.fillText(`◆ ${gems}   ☠ ${kills}   ⚡ ${Math.floor(distance)}M`,W-330,50);if(elapsed<9000){ctx.fillStyle="#07101bd9";ctx.fillRect(W/2-285,innerHeight-72,570,42);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.fillText("A/D MOVE · SPACE JUMP · S SLIDE · SHIFT DASH · J MELEE · K THROW",W/2,innerHeight-45);ctx.textAlign="left"}if(b){ctx.fillStyle=o.world.color;ctx.fillText(`BOSS ${b.hp}/${b.max}`,W/2-45,38)}}
 function tick(now:number){if(stopped)return;const dt=Math.min((now-last)/1000,.034);last=now;elapsed+=dt*1000;update(dt,now);draw(now);if(!stopped)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);return cleanup;
}
