"use client";
import {useCallback,useEffect,useRef,useState} from "react";
declare global{interface Window{ethereum?:{request:(a:{method:string;params?:unknown[]})=>Promise<unknown>}}}
const CHAIN={id:46630,hex:"0xb626",name:"Robinhood Chain Testnet",rpc:"https://rpc.testnet.chain.robinhood.com",explorer:"https://explorer.testnet.chain.robinhood.com"};
const RUNNERS=[{id:"byte",name:"BYTE",color:"#b6ff33",cost:0,perk:"BALANCED"},{id:"nova",name:"NOVA",color:"#65f8ff",cost:20,perk:"+25% SHARDS"},{id:"ember",name:"EMBER",color:"#ff6b4a",cost:35,perk:"+1 HEART"},{id:"void",name:"VOID",color:"#ad7aff",cost:50,perk:"HIGH JUMP"}];
const GEAR=[{id:"blade",name:"PULSE BLADE",cost:0,perk:"RANGE 100"},{id:"boots",name:"GRAV BOOTS",cost:15,perk:"HIGH JUMP"},{id:"shield",name:"HEX SHIELD",cost:30,perk:"+1 HEART"},{id:"magnet",name:"SHARD MAGNET",cost:45,perk:"2× GEMS"}];
type Score={rank:number;address:string;score:number;gems:number;rekt:number};type Run={id:string;token:string};type Profile={shards:number;runner:string;gear:string;unlockedRunners:string[];unlockedGear:string[]};
const empty:Profile={shards:0,runner:"byte",gear:"blade",unlockedRunners:["byte"],unlockedGear:["blade"]};
export default function GameClient(){const canvas=useRef<HTMLCanvasElement>(null),raf=useRef(0),keys=useRef(new Set<string>()),run=useRef<Run|null>(null);const[wallet,setWallet]=useState("");const[status,setStatus]=useState("CONNECT WALLET TO PLAY");const[playing,setPlaying]=useState(false);const[menu,setMenu]=useState<"home"|"loadout"|"board">("home");const[profile,setProfile]=useState<Profile>(empty);const[scores,setScores]=useState<Score[]>([]);const[stats,setStats]=useState({score:0,distance:0,gems:0,rekt:0});
 const board=useCallback(async()=>{const r=await fetch("/api/leaderboard",{cache:"no-store"});if(r.ok)setScores((await r.json()).scores)},[]);useEffect(()=>{board()},[board]);
 async function connect(){try{if(!window.ethereum)throw new Error("Install Robinhood Wallet or an EVM wallet");setStatus("CHECK WALLET…");const a=await window.ethereum.request({method:"eth_requestAccounts"})as string[];const address=a[0];const chain=await window.ethereum.request({method:"eth_chainId"})as string;if(parseInt(chain,16)!==CHAIN.id){try{await window.ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:CHAIN.hex}]})}catch{await window.ethereum.request({method:"wallet_addEthereumChain",params:[{chainId:CHAIN.hex,chainName:CHAIN.name,nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18},rpcUrls:[CHAIN.rpc],blockExplorerUrls:[CHAIN.explorer]}]})}}const c=await fetch("/api/auth/challenge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address})});const{message}=await c.json();const signature=await window.ethereum.request({method:"personal_sign",params:[message,address]})as string;const v=await fetch("/api/auth/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address,message,signature})});if(!v.ok)throw new Error("Signature rejected");setWallet(address);setStatus("READY TO RUN");const p=await fetch("/api/profile");if(p.ok)setProfile((await p.json()).profile)}catch(e){setStatus(e instanceof Error?e.message:"Wallet failed")}}
 async function equip(type:"runner"|"gear",id:string,cost:number){if(!wallet)return connect();const r=await fetch("/api/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,id,cost})});const j=await r.json();if(r.ok)setProfile(j.profile);else setStatus(j.error||"Unlock failed")}
 const start=useCallback(async()=>{if(!wallet)return connect();const r=await fetch("/api/run/start",{method:"POST"});if(!r.ok){setWallet("");setStatus("SESSION EXPIRED");return}run.current=await r.json();setStats({score:0,distance:0,gems:0,rekt:0});setPlaying(true);setMenu("home");setStatus("RUN LIVE")},[wallet]);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current.add(e.code);if(["Space","ArrowUp"].includes(e.code))e.preventDefault()},u=(e:KeyboardEvent)=>keys.current.delete(e.code);addEventListener("keydown",d);addEventListener("keyup",u);return()=>{removeEventListener("keydown",d);removeEventListener("keyup",u)}},[]);
 useEffect(()=>{if(!playing||!canvas.current)return;const c=canvas.current,x=c.getContext("2d")!;let last=performance.now(),elapsed=0,spawn=.5,gspawn=.2,distance=0,rekt=0,gems=0,dead=false;const runner=RUNNERS.find(r=>r.id===profile.runner)!,gear=GEAR.find(g=>g.id===profile.gear)!;const hpBonus=runner.id==="ember"||gear.id==="shield"?1:0,jumpBonus=runner.id==="void"||gear.id==="boots"?1.17:1,gemBonus=runner.id==="nova"?1.25:gear.id==="magnet"?2:1,range=gear.id==="blade"?115:92;const p={x:90,y:200,vy:0,w:30,h:38,hp:3+hpBonus};let enemies:{x:number;y:number;s:number}[]=[],shards:{x:number;y:number}[]=[];const resize=()=>{const d=Math.min(devicePixelRatio,2);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0)};resize();addEventListener("resize",resize);
 const finish=async()=>{if(dead)return;dead=true;cancelAnimationFrame(raf.current);setPlaying(false);const score=Math.floor(distance+gems*120+rekt*200);setStats({score,distance:Math.floor(distance),gems,rekt});setStatus("VERIFYING RUN…");const r=await fetch("/api/run/finish",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({run:run.current,durationMs:Math.floor(elapsed),distance:Math.floor(distance),gems,rekt,score})});setStatus(r.ok?"SCORE VERIFIED — SHARDS BANKED":"RUN REJECTED");if(r.ok){const q=await fetch("/api/profile");if(q.ok)setProfile((await q.json()).profile);board()}};
 const loop=(now:number)=>{const dt=Math.min((now-last)/1e3,.034);last=now;elapsed+=dt*1e3;const W=innerWidth,H=innerHeight,ground=H-85;distance+=dt*42;if((keys.current.has("Space")||keys.current.has("KeyW")||keys.current.has("ArrowUp"))&&p.y>=ground-p.h-2)p.vy=-520*jumpBonus;p.vy+=1300*dt;p.y=Math.min(ground-p.h,p.y+p.vy*dt);spawn-=dt;if(spawn<=0){enemies.push({x:W+30,y:ground-34,s:30+Math.random()*12});spawn=Math.max(.6,1.45-distance/1900)}gspawn-=dt;if(gspawn<=0){shards.push({x:W+20,y:ground-80-Math.random()*150});gspawn=.75+Math.random()*.7}enemies.forEach(e=>e.x-=(220+distance/18)*dt);shards.forEach(g=>g.x-=(215+distance/19)*dt);enemies=enemies.filter(e=>{if(e.x<p.x+p.w&&e.x+e.s>p.x&&p.y+p.h>e.y){p.hp--;e.x=-100;if(p.hp<=0)finish()}return e.x>-60});shards=shards.filter(g=>{if(g.x<p.x+p.w+12&&g.x+16>p.x-12&&p.y<g.y+16&&p.y+p.h>g.y){gems+=gemBonus;return false}return g.x>-30});if(keys.current.has("KeyX")||keys.current.has("KeyK")){const hit=enemies.find(e=>e.x>p.x&&e.x<p.x+range&&Math.abs(e.y-p.y)<55);if(hit){hit.x=-100;rekt++;keys.current.delete("KeyX");keys.current.delete("KeyK")}}const score=Math.floor(distance+gems*120+rekt*200);setStats({score,distance:Math.floor(distance),gems:Math.floor(gems),rekt});x.fillStyle="#06100c";x.fillRect(0,0,W,H);x.strokeStyle="#173a2a";for(let gx=(-distance*3)%54;gx<W;gx+=54){x.beginPath();x.moveTo(gx,0);x.lineTo(gx,H);x.stroke()}for(let gy=20;gy<H;gy+=54){x.beginPath();x.moveTo(0,gy);x.lineTo(W,gy);x.stroke()}x.fillStyle="#b6ff33";x.fillRect(0,ground,W,3);x.shadowBlur=22;x.shadowColor=runner.color;x.fillStyle=runner.color;x.fillRect(p.x,p.y,p.w,p.h);x.fillStyle="#06100c";x.fillRect(p.x+18,p.y+9,6,6);x.shadowBlur=0;enemies.forEach(e=>{x.fillStyle="#ff536f";x.fillRect(e.x,e.y,e.s,e.s)});shards.forEach(g=>{x.save();x.translate(g.x+8,g.y+8);x.rotate(now/400);x.fillStyle="#65f8ff";x.fillRect(-7,-7,14,14);x.restore()});x.fillStyle="#eaffef";x.font="700 14px monospace";x.fillText(`${runner.name} · ${gear.name}     HP ${"■".repeat(p.hp)}     SCORE ${score}`,24,34);if(!dead)raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf.current);removeEventListener("resize",resize)}},[playing,profile,board]);
 return <main className="playPage"><canvas ref={canvas}/><div className="gameTop"><a href="/" className="brand"><span>R</span>REKTRUN</a><div className="hud"><b>{stats.score.toLocaleString()}</b><small>SCORE</small></div><button className="miniWallet" onClick={connect}>{wallet?`${wallet.slice(0,6)}…${wallet.slice(-4)}`:"CONNECT"}</button></div>{!playing&&<div className="gameMenu"><div className="menuPanel"><div className="eyebrow">ROBINHOOD CHAIN // SEASON ZERO</div><h1>READY,<br/><i>RUNNER?</i></h1><p className="gameStatus">{status}</p><div className="menuActions"><button className="play" onClick={start}>{wallet?"START RUN":"CONNECT WALLET"}</button><button onClick={()=>setMenu("loadout")}>LOADOUT</button><button onClick={()=>{setMenu("board");board()}}>RANKS</button></div><small>SPACE / W — JUMP · X / K — ATTACK</small></div>{menu==="loadout"&&<Loadout profile={profile} equip={equip} close={()=>setMenu("home")}/>} {menu==="board"&&<Board scores={scores} close={()=>setMenu("home")}/>}</div>}<div className="gameBottom"><span>{RUNNERS.find(r=>r.id===profile.runner)?.name} / {GEAR.find(g=>g.id===profile.gear)?.name}</span><span>{profile.shards} ◆ BANKED</span></div></main>}
function Loadout({profile,equip,close}:{profile:Profile;equip:(t:"runner"|"gear",id:string,cost:number)=>void;close:()=>void}){return <aside className="drawer"><button className="close" onClick={close}>×</button><div className="eyebrow">CUSTOMIZE YOUR RUN</div><h2>LOADOUT</h2><h3>RUNNER</h3><div className="itemGrid">{RUNNERS.map(r=><button key={r.id} className={profile.runner===r.id?"selected":""} onClick={()=>equip("runner",r.id,r.cost)}><i style={{background:r.color}}>{r.name[0]}</i><b>{r.name}</b><small>{profile.unlockedRunners.includes(r.id)?r.perk:`${r.cost} ◆`}</small></button>)}</div><h3>GEAR</h3><div className="itemGrid gear">{GEAR.map(g=><button key={g.id} className={profile.gear===g.id?"selected":""} onClick={()=>equip("gear",g.id,g.cost)}><i>+</i><b>{g.name}</b><small>{profile.unlockedGear.includes(g.id)?g.perk:`${g.cost} ◆`}</small></button>)}</div><div className="bank">BANKED SHARDS <b>{profile.shards} ◆</b></div></aside>}
function Board({scores,close}:{scores:Score[];close:()=>void}){return <aside className="drawer"><button className="close" onClick={close}>×</button><div className="eyebrow">VERIFIED RUNS</div><h2>TOP 100</h2><div className="rankList">{scores.length?scores.slice(0,12).map(s=><div key={s.address}><b>#{s.rank}</b><span>{s.address.slice(0,7)}…{s.address.slice(-4)}</span><strong>{s.score.toLocaleString()}</strong></div>):<p>NO RUNS YET.</p>}</div></aside>}
