"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {startArcadeGame} from "./arcadeEngine";
import {setAudioEnabled,startMusic,unlockAudio} from "./gameAudio";

declare global{interface Window{ethereum?:{request:(a:{method:string;params?:unknown[]})=>Promise<unknown>}}}
const CHAIN={id:46630,hex:"0xb626",name:"Robinhood Chain Testnet",rpc:"https://rpc.testnet.chain.robinhood.com",explorer:"https://explorer.testnet.chain.robinhood.com"};
const RUNNERS=[
 {id:"byte",name:"BYTE",color:"#b6ff33",cost:0,perk:"BALANCED",face:"B"},
 {id:"nova",name:"NOVA",color:"#65f8ff",cost:20,perk:"DOUBLE SHARDS",face:"N"},
 {id:"ember",name:"EMBER",color:"#ff6b4a",cost:35,perk:"EXTRA HEART",face:"E"},
 {id:"void",name:"VOID",color:"#ad7aff",cost:50,perk:"HIGH JUMP",face:"V"}
];
const GEAR=[{id:"blade",name:"PULSE BLADE",cost:0,perk:"LONG RANGE"},{id:"boots",name:"GRAV BOOTS",cost:15,perk:"HIGH JUMP"},{id:"shield",name:"HEX SHIELD",cost:30,perk:"EXTRA HEART"},{id:"magnet",name:"SHARD MAGNET",cost:45,perk:"DOUBLE SHARDS"}];
const BOSSES=[
 {id:"base",name:"IRON MAW",color:"#37d5ff",sky:"#071b3b",land:"#164f80",desc:"THE FROZEN MACHINE"},
 {id:"forest",name:"MOSS TITAN",color:"#64ff7c",sky:"#092a20",land:"#17633d",desc:"THE ROOTED COLOSSUS"},
 {id:"lava",name:"CINDER KING",color:"#ff9d24",sky:"#310b13",land:"#8f241b",desc:"THE FORGE TYRANT"},
 {id:"cosmic",name:"VOID WING",color:"#b04cff",sky:"#160923",land:"#45145f",desc:"THE STAR EATER"}
];
type Screen="loading"|"title"|"story"|"runner"|"boss"|"game"|"result"|"ranks";
type Score={rank:number;address:string;score:number;gems:number;rekt:number};type Run={id:string;token:string};
type Profile={shards:number;runner:string;gear:string;unlockedRunners:string[];unlockedGear:string[]};
const empty:Profile={shards:0,runner:"byte",gear:"blade",unlockedRunners:["byte"],unlockedGear:["blade"]};

export default function GameClient(){
 const canvas=useRef<HTMLCanvasElement>(null),raf=useRef(0),keys=useRef(new Set<string>()),run=useRef<Run|null>(null);
 const[screen,setScreen]=useState<Screen>("loading"),[loading,setLoading]=useState(0),[wallet,setWallet]=useState(""),[status,setStatus]=useState("WALLET REQUIRED");
 const[profile,setProfile]=useState<Profile>(empty),[runnerIndex,setRunnerIndex]=useState(0),[bossIndex,setBossIndex]=useState(0),[gearOpen,setGearOpen]=useState(false);
 const[scores,setScores]=useState<Score[]>([]),[stats,setStats]=useState({score:0,distance:0,gems:0,rekt:0}),[soundOn,setSoundOn]=useState(true);
 const board=useCallback(async()=>{const r=await fetch("/api/leaderboard",{cache:"no-store"});if(r.ok)setScores((await r.json()).scores)},[]);
 useEffect(()=>{let p=0;const t=setInterval(()=>{p+=10;setLoading(p);if(p>=100){clearInterval(t);setTimeout(()=>setScreen("title"),180)}},55);return()=>clearInterval(t)},[]);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current.add(e.code);if(["Space","ArrowUp"].includes(e.code))e.preventDefault()},u=(e:KeyboardEvent)=>keys.current.delete(e.code);addEventListener("keydown",d);addEventListener("keyup",u);return()=>{removeEventListener("keydown",d);removeEventListener("keyup",u)}},[]);
 async function connect(){try{if(!window.ethereum)throw new Error("INSTALL ROBINHOOD WALLET OR AN EVM WALLET");setStatus("CHECK WALLET...");const a=await window.ethereum.request({method:"eth_requestAccounts"})as string[];const address=a[0];const chain=await window.ethereum.request({method:"eth_chainId"})as string;if(parseInt(chain,16)!==CHAIN.id){try{await window.ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:CHAIN.hex}]})}catch{await window.ethereum.request({method:"wallet_addEthereumChain",params:[{chainId:CHAIN.hex,chainName:CHAIN.name,nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18},rpcUrls:[CHAIN.rpc],blockExplorerUrls:[CHAIN.explorer]}]})}}const c=await fetch("/api/auth/challenge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address})});const{message}=await c.json();const signature=await window.ethereum.request({method:"personal_sign",params:[message,address]})as string;const v=await fetch("/api/auth/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address,message,signature})});if(!v.ok)throw new Error("SIGNATURE REJECTED");setWallet(address);setStatus("WALLET VERIFIED");const p=await fetch("/api/profile");if(p.ok){const next=(await p.json()).profile;setProfile(next);setRunnerIndex(Math.max(0,RUNNERS.findIndex(r=>r.id===next.runner)))}return true}catch(e){setStatus(e instanceof Error?e.message:"WALLET FAILED");return false}}
 async function play(){unlockAudio();startMusic();if(!wallet&&!(await connect()))return;setScreen("story")}
 async function chooseRunner(){const r=RUNNERS[runnerIndex];if(await saveEquip("runner",r.id,r.cost))setScreen("boss")}
 async function saveEquip(type:"runner"|"gear",id:string,cost:number){const r=await fetch("/api/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,id,cost})});const j=await r.json();if(r.ok){setProfile(j.profile);setStatus("LOADOUT SAVED");return true}else{setStatus(j.error||"LOCKED");return false}}
 async function startRun(){unlockAudio();startMusic();const r=await fetch("/api/run/start",{method:"POST"});if(!r.ok){setWallet("");setScreen("title");setStatus("SESSION EXPIRED");return}run.current=await r.json();setStats({score:0,distance:0,gems:0,rekt:0});setScreen("game")}

 useEffect(()=>{if(screen!=="game"||!canvas.current)return;const selectedRunner=RUNNERS.find(r=>r.id===profile.runner)||RUNNERS[0],selectedGear=GEAR.find(g=>g.id===profile.gear)||GEAR[0];return startArcadeGame(canvas.current,keys.current,{world:BOSSES[bossIndex],runner:selectedRunner,gear:selectedGear,onStats:setStats,onFinish:async(s,durationMs)=>{setStats(s);setScreen("result");setStatus("VERIFYING RUN...");const r=await fetch("/api/run/finish",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({run:run.current,durationMs,distance:s.distance,gems:s.gems,rekt:s.rekt,score:s.score})});setStatus(r.ok?"SCORE VERIFIED — SHARDS BANKED":"RUN REJECTED");if(r.ok){const q=await fetch("/api/profile");if(q.ok)setProfile((await q.json()).profile);board()}}})},[screen,profile,bossIndex,board]);

 useEffect(()=>{if(screen==="game")return;if(screen!=="game"||!canvas.current)return;const c=canvas.current,x=c.getContext("2d")!;let last=performance.now(),elapsed=0,spawn=.8,gspawn=.3,distance=0,rekt=0,gems=0,dead=false,bossHp=8,bossActive=false;const runner=RUNNERS.find(r=>r.id===profile.runner)||RUNNERS[0],gear=GEAR.find(g=>g.id===profile.gear)||GEAR[0],world=BOSSES[bossIndex];const hpBonus=runner.id==="ember"||gear.id==="shield"?1:0,jumpBonus=runner.id==="void"||gear.id==="boots"?1.18:1,gemBonus=runner.id==="nova"||gear.id==="magnet"?2:1,range=gear.id==="blade"?125:95;const p={x:120,y:200,vy:0,w:42,h:54,hp:4+hpBonus,max:4+hpBonus};let enemies:{x:number;y:number;s:number}[]=[],shards:{x:number;y:number}[]=[];const resize=()=>{const d=Math.min(devicePixelRatio,2);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0)};resize();addEventListener("resize",resize);
 const finish=async()=>{if(dead)return;dead=true;cancelAnimationFrame(raf.current);const score=Math.floor(distance+gems*120+rekt*200);setStats({score,distance:Math.floor(distance),gems,rekt});setScreen("result");setStatus("VERIFYING RUN...");const r=await fetch("/api/run/finish",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({run:run.current,durationMs:Math.floor(elapsed),distance:Math.floor(distance),gems,rekt,score})});setStatus(r.ok?"SCORE VERIFIED — SHARDS BANKED":"RUN REJECTED");if(r.ok){const q=await fetch("/api/profile");if(q.ok)setProfile((await q.json()).profile);board()}};
 const loop=(now:number)=>{const dt=Math.min((now-last)/1000,.034);last=now;elapsed+=dt*1000;const W=innerWidth,H=innerHeight,ground=H-105;distance+=dt*48;if(distance>650)bossActive=true;if((keys.current.has("Space")||keys.current.has("KeyW")||keys.current.has("ArrowUp"))&&p.y>=ground-p.h-2)p.vy=-540*jumpBonus;p.vy+=1350*dt;p.y=Math.min(ground-p.h,p.y+p.vy*dt);spawn-=dt;if(spawn<=0&&!bossActive){enemies.push({x:W+30,y:ground-38,s:34+Math.random()*16});spawn=Math.max(.62,1.35-distance/2000)}gspawn-=dt;if(gspawn<=0&&!bossActive){shards.push({x:W+20,y:ground-90-Math.random()*170});gspawn=.65+Math.random()*.8}enemies.forEach(e=>e.x-=(230+distance/20)*dt);shards.forEach(g=>g.x-=(220+distance/22)*dt);enemies=enemies.filter(e=>{if(e.x<p.x+p.w&&e.x+e.s>p.x&&p.y+p.h>e.y){p.hp--;e.x=-100;if(p.hp<=0)finish()}return e.x>-60});shards=shards.filter(g=>{if(g.x<p.x+p.w+14&&g.x+16>p.x-14&&p.y<g.y+16&&p.y+p.h>g.y){gems+=gemBonus;return false}return g.x>-30});if(keys.current.has("KeyX")||keys.current.has("KeyK")){const hit=enemies.find(e=>e.x>p.x&&e.x<p.x+range&&Math.abs(e.y-p.y)<60);if(hit){hit.x=-100;rekt++}else if(bossActive){bossHp--;rekt++;if(bossHp<=0)finish()}keys.current.delete("KeyX");keys.current.delete("KeyK")}const score=Math.floor(distance+gems*120+rekt*200);setStats({score,distance:Math.floor(distance),gems,rekt});drawWorld(x,W,H,ground,world,distance,now);drawRunner(x,p.x,p.y,runner.color,now);enemies.forEach(e=>drawEnemy(x,e.x,e.y,e.s,world.color));shards.forEach(g=>drawShard(x,g.x,g.y,now));if(bossActive)drawBoss(x,W-230,ground-190,world.color,bossHp);drawHud(x,W,p.hp,p.max,gems,rekt,distance,world.color,bossActive?bossHp:0);if(!dead)raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf.current);removeEventListener("resize",resize)}},[screen,profile,bossIndex,board]);

 const runner=RUNNERS[runnerIndex],boss=BOSSES[bossIndex];
 return <main className={`pixelGame world-${boss.id}`}>
  <canvas ref={canvas}/>
  {screen!=="loading"&&<button className="soundToggle" aria-label={soundOn?"Mute audio":"Enable audio"} onClick={()=>{const next=!soundOn;setSoundOn(next);setAudioEnabled(next)}}>{soundOn?"♪":"×"}</button>}
  {screen!=="loading"&&screen!=="game"&&<div className="pixelBrand">R<i>⚡</i></div>}
  {screen==="loading"&&<div className="loadingScreen"><b>LOADING GAME...</b><div><i style={{width:`${loading}%`}}/></div><span>{loading}%</span></div>}
  {screen==="title"&&<div className="pixelScene titleScene"><div className="pixelStars"/><button className="hamb" onClick={()=>{board();setScreen("ranks")}}>☰</button><div className="titleCrew">{RUNNERS.map((r,i)=><i key={r.id} className="runnerSprite" style={{"--sprite-x":`${i*33.333}%`} as React.CSSProperties}/>)}</div><div className="gameLogo">REKT<span>RUN</span><small>v0.4</small></div><button className="pixelBtn main" onClick={play}>PLAY</button><button className="pixelBtn credits" onClick={()=>location.href="/"}>ABOUT</button><button className="connectCorner" onClick={connect}>{wallet?`${wallet.slice(0,6)}...${wallet.slice(-4)}`:"CONNECT WALLET"}</button><p className="pixelStatus">{status}</p></div>}
  {screen==="story"&&<div className="pixelScene storyScene"><button className="hamb">☰</button><div className="dialog"><p>“ THE CHAIN FRACTURED. FOUR RUNNERS ANSWERED THE SIGNAL... ”</p></div><div className="storyBots"><i/><i/></div><button className="pixelBtn skip" onClick={()=>setScreen("runner")}>SKIP</button><button className="pixelBtn next" onClick={()=>setScreen("runner")}>NEXT</button></div>}
  {screen==="runner"&&<div className="pixelScene selectScene"><button className="hamb" onClick={()=>setScreen("title")}>☰</button><div className="selectTitle">⚡ SELECT YOUR RUNNER ⚡</div><div className="banked">MY SHARDS <b>◆ {profile.shards}</b></div><div className="sideRunners">{RUNNERS.map((r,i)=><i className="runnerSprite" key={r.id} style={{"--sprite-x":`${i*33.333}%`,opacity:i===runnerIndex?1:.45,animationDelay:`${-.37*i}s`} as React.CSSProperties}/>)}</div><div className="chosenRunner" style={{"--runner":runner.color,"--sprite-x":`${runnerIndex*33.333}%`} as React.CSSProperties}><i key={runner.id} className="runnerSprite"/><h2>{runner.name}</h2><p>{runner.perk}</p>{!profile.unlockedRunners.includes(runner.id)&&<b className="locked">🔒 {runner.cost} ◆</b>}</div><button className="arrow left" onClick={()=>setRunnerIndex((runnerIndex+RUNNERS.length-1)%RUNNERS.length)}>‹</button><button className="arrow right" onClick={()=>setRunnerIndex((runnerIndex+1)%RUNNERS.length)}>›</button><button className="pixelBtn back" onClick={()=>setScreen("title")}>BACK</button><button className="pixelBtn select" onClick={chooseRunner}>SELECT</button><button className="gearLink" onClick={()=>setGearOpen(true)}>EQUIPMENT</button></div>}
  {screen==="boss"&&<div className="pixelScene bossScene" style={{"--boss":boss.color,"--sky":boss.sky,"--land":boss.land} as React.CSSProperties}><button className="hamb" onClick={()=>setScreen("title")}>☰</button><div className="selectTitle">⚡ SELECT BOSS ⚡</div><div className="bossLine">{BOSSES.map((b,i)=><i key={b.id} className={`bossSprite ${i===bossIndex?"active":""}`} style={{"--c":b.color,"--sprite-x":`${i*33.333}%`,animationDelay:`${-.43*i}s`} as React.CSSProperties}/>)}</div><div className="chosenBoss" style={{"--sprite-x":`${bossIndex*33.333}%`} as React.CSSProperties}><i key={boss.id} className="bossSprite"/><h2>{boss.name}</h2><p>{boss.desc}</p></div><button className="arrow left" onClick={()=>setBossIndex((bossIndex+BOSSES.length-1)%BOSSES.length)}>‹</button><button className="arrow right" onClick={()=>setBossIndex((bossIndex+1)%BOSSES.length)}>›</button><button className="pixelBtn back" onClick={()=>setScreen("runner")}>BACK</button><button className="pixelBtn select" onClick={startRun}>FIGHT</button></div>}
  {screen==="result"&&<div className="pixelOverlay"><div className="resultCard"><small>RUN COMPLETE</small><h2>{stats.score.toLocaleString()}</h2><p>SCORE</p><div><span>{stats.distance}M<br/><small>DISTANCE</small></span><span>{stats.gems} ◆<br/><small>SHARDS</small></span><span>{stats.rekt}<br/><small>REKT</small></span></div><b>{status}</b><button className="pixelBtn main" onClick={()=>setScreen("boss")}>RUN AGAIN</button><button className="textBtn" onClick={()=>{board();setScreen("ranks")}}>LEADERBOARD</button></div></div>}
  {screen==="ranks"&&<div className="pixelOverlay"><div className="rankPanel"><button className="close" onClick={()=>setScreen("title")}>×</button><small>VERIFIED RUNS</small><h2>LEADERBOARD</h2>{scores.slice(0,10).map(s=><div key={s.address}><b>#{s.rank}</b><span>{s.address.slice(0,8)}...{s.address.slice(-4)}</span><strong>{s.score.toLocaleString()}</strong></div>)}</div></div>}
  {gearOpen&&<GearShop profile={profile} save={saveEquip} close={()=>setGearOpen(false)}/>}
 </main>
}

function GearShop({profile,save,close}:{profile:Profile;save:(t:"runner"|"gear",id:string,cost:number)=>Promise<boolean>;close:()=>void}){return <div className="pixelOverlay gearOverlay"><div className="gearPanel"><button className="close" onClick={close}>×</button><small>EQUIPMENT LOCKER</small><h2>CHOOSE GEAR</h2><div>{GEAR.map(g=><button key={g.id} className={profile.gear===g.id?"active":""} onClick={()=>save("gear",g.id,g.cost)}><i>{g.id==="blade"?"⚔":g.id==="boots"?"⌁":g.id==="shield"?"⬡":"∩"}</i><b>{g.name}</b><small>{profile.unlockedGear.includes(g.id)?g.perk:`LOCKED · ${g.cost} ◆`}</small></button>)}</div><p>BANKED ◆ {profile.shards}</p></div></div>}

function drawWorld(x:CanvasRenderingContext2D,W:number,H:number,ground:number,w:typeof BOSSES[number],d:number,n:number){x.fillStyle=w.sky;x.fillRect(0,0,W,H);x.fillStyle="#ffffff";for(let i=0;i<65;i++){const sx=(i*137-d*(i%3+1)*.2)%W,sy=(i*71)%(ground*.62);x.fillRect(sx,sy,i%7===0?3:1,i%7===0?3:1)}x.fillStyle=w.land;for(let i=0;i<9;i++){const bx=i*260-(d*1.5)%260;x.beginPath();x.moveTo(bx,ground);x.lineTo(bx+120,ground-190-(i%3)*45);x.lineTo(bx+260,ground);x.fill()}x.fillStyle="#07101b";for(let i=0;i<15;i++){const tx=i*110-(d*2.5)%110;x.fillRect(tx,ground-100,15,100);x.beginPath();x.moveTo(tx-30,ground-60);x.lineTo(tx+8,ground-150);x.lineTo(tx+45,ground-60);x.fill()}x.fillStyle=w.color;x.fillRect(0,ground,W,6);x.fillStyle="#0b1420";x.fillRect(0,ground+6,W,H-ground);x.strokeStyle=w.color;x.globalAlpha=.25;for(let g=0;g<W;g+=55){x.beginPath();x.moveTo(g-(d*4)%55,ground);x.lineTo(g-(d*4)%55,H);x.stroke()}x.globalAlpha=1}
function drawRunner(x:CanvasRenderingContext2D,px:number,py:number,c:string,n:number){x.fillStyle=c;x.fillRect(px+5,py,32,18);x.fillRect(px,py+18,42,28);x.fillRect(px+5,py+46,12,10);x.fillRect(px+27,py+46,12,10);x.fillStyle="#07110d";x.fillRect(px+27,py+7,6,6);x.fillStyle="#fff";x.fillRect(px+7,py+24,8,5);x.shadowBlur=18;x.shadowColor=c;x.strokeStyle=c;x.strokeRect(px-3,py-3,48,62);x.shadowBlur=0}
function drawEnemy(x:CanvasRenderingContext2D,px:number,py:number,s:number,c:string){x.fillStyle="#131018";x.fillRect(px,py,s,s);x.strokeStyle=c;x.lineWidth=3;x.strokeRect(px,py,s,s);x.fillStyle=c;x.fillRect(px+7,py+9,6,6);x.fillRect(px+s-13,py+9,6,6)}
function drawShard(x:CanvasRenderingContext2D,px:number,py:number,n:number){x.save();x.translate(px+8,py+8);x.rotate(n/400);x.fillStyle="#65f8ff";x.fillRect(-8,-8,16,16);x.restore()}
function drawBoss(x:CanvasRenderingContext2D,px:number,py:number,c:string,hp:number){x.shadowBlur=30;x.shadowColor=c;x.fillStyle="#10121a";x.fillRect(px,py,145,150);x.strokeStyle=c;x.lineWidth=6;x.strokeRect(px,py,145,150);x.fillStyle=c;x.fillRect(px+28,py+38,26,18);x.fillRect(px+91,py+38,26,18);x.fillRect(px+38,py+95,70,16);x.shadowBlur=0;x.fillStyle="#07110d";x.fillRect(px,py-28,145,12);x.fillStyle=c;x.fillRect(px,py-28,145*(hp/8),12)}
function drawHud(x:CanvasRenderingContext2D,W:number,hp:number,max:number,g:number,r:number,d:number,c:string,boss:number){x.fillStyle="#070b14dd";x.fillRect(20,20,220,68);x.strokeStyle=c;x.lineWidth=3;x.strokeRect(20,20,220,68);x.fillStyle="#ff48d7";x.font="26px monospace";x.fillText("♥".repeat(hp),42,63);x.fillStyle="#fff";x.font="700 18px monospace";x.fillText(`◆ ${g}   ☠ ${r}   ⚑ ${Math.floor(d)}M`,W-330,52);if(boss){x.fillStyle=c;x.font="700 13px monospace";x.fillText("BOSS ENGAGED",W/2-60,35)}}
